#pragma once

#include "cimgui/cimgui.h"

#ifdef __cplusplus
extern "C" {
#endif

extern ImGuiID GetID_Str(const char* str_id);
extern ImGuiID GetID_StrStr(const char* str_id_begin,const char* str_id_end);
extern ImGuiID GetID_Ptr(const void* ptr_id);
extern ImGuiInputTextCallbackData* InputTextCallbackData_ImGuiInputTextCallbackData();
extern void TableColumn_Destroy(ImGuiTableColumn* self);
extern bool DragInt3V(const char* label,int v[3],float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void Font_AddRemapCharV(ImFont* self,ImWchar dst,ImWchar src,bool overwrite_dst);
extern bool Payload_IsPreview(ImGuiPayload* self);
extern bool ColorEdit3V(const char* label,float col[3],ImGuiColorEditFlags flags);
extern void EndFrame();
extern void IO_Destroy(ImGuiIO* self);
extern float GetWindowWidth();
extern ImGuiID DockSpaceV(ImGuiID id,const ImVec2 size,ImGuiDockNodeFlags flags,const ImGuiWindowClass* window_class);
extern void ShowMetricsWindowV(bool* p_open);
extern void SameLineV(float offset_from_start_x,float spacing);
extern void FontGlyphRangesBuilder_SetBit(ImFontGlyphRangesBuilder* self,size_t n);
extern const char* GetClipboardText();
extern void DrawList_AddImageV(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p_min,const ImVec2 p_max,const ImVec2 uv_min,const ImVec2 uv_max,ImU32 col);
extern void TableTempData_Destroy(ImGuiTableTempData* self);
extern bool DebugCheckVersionAndDataLayout(const char* version_str,size_t sz_io,size_t sz_style,size_t sz_vec2,size_t sz_vec4,size_t sz_drawvert,size_t sz_drawidx);
extern bool IsItemActive();
extern bool IsMouseDoubleClicked(ImGuiMouseButton button);
extern void FontAtlas_ClearTexData(ImFontAtlas* self);
extern void Font_GrowIndex(ImFont* self,int new_size);
extern void IO_AddInputCharacter(ImGuiIO* self,unsigned int c);
extern void MemFree(void* ptr);
extern void DebugTextEncoding(const char* text);
extern void EndTabItem();
extern void SetClipboardText(const char* text);
extern void UpdatePlatformWindows();
extern void TableSettings_Destroy(ImGuiTableSettings* self);
extern void CalcTextSizeV(ImVec2 *pOut,const char* text,bool hide_text_after_double_hash,float wrap_width);
extern void TextBuffer_AppendV(ImGuiTextBuffer* self,const char* str,const char* str_end);
extern void SetMouseCursor(ImGuiMouseCursor cursor_type);
extern void SetWindowPos_Vec2V(const ImVec2 pos,ImGuiCond cond);
extern void SetWindowPos_StrV(const char* name,const ImVec2 pos,ImGuiCond cond);
extern ImFont* FontAtlas_AddFont(ImFontAtlas* self,const ImFontConfig* font_cfg);
extern void PushItemWidth(float item_width);
extern void ListClipper_BeginV(ImGuiListClipper* self,int items_count,float items_height);
extern bool IsItemEdited();
extern void Value_Bool(const char* prefix,bool b);
extern void Value_Int(const char* prefix,int v);
extern void Value_Uint(const char* prefix,unsigned int v);
extern void Value_FloatV(const char* prefix,float v,const char* float_format);
extern bool TableNextColumn();
extern bool InvisibleButtonV(const char* str_id,const ImVec2 size,ImGuiButtonFlags flags);
extern void DrawList_AddLineV(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,ImU32 col,float thickness);
extern void DrawList_PathFillConvex(ImDrawList* self,ImU32 col);
extern ImFont* FontAtlas_AddFontFromMemoryCompressedTTFV(ImFontAtlas* self,const void* compressed_font_data,int compressed_font_size,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern void NextWindowData_Destroy(ImGuiNextWindowData* self);
extern void GetItemRectMax(ImVec2 *pOut);
extern bool InputScalarV(const char* label,ImGuiDataType data_type,void* p_data,const void* p_step,const void* p_step_fast,const char* format,ImGuiInputTextFlags flags);
extern ImFontAtlasCustomRect* FontAtlas_GetCustomRectByIndex(ImFontAtlas* self,int index);
extern void FontAtlas_GetTexDataAsAlpha8V(ImFontAtlas* self,unsigned char** out_pixels,int* out_width,int* out_height,int* out_bytes_per_pixel);
extern void StyleColorsLightV(ImGuiStyle* dst);
extern const ImFontGlyph* Font_FindGlyphNoFallback(ImFont* self,ImWchar c);
extern const char* GetKeyName(ImGuiKey key);
extern bool SliderAngleV(const char* label,float* v_rad,float v_degrees_min,float v_degrees_max,const char* format,ImGuiSliderFlags flags);
extern void Text(const char* fmt);
extern void DrawList_AddNgonFilled(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments);
extern void DrawList_PathArcToV(ImDrawList* self,const ImVec2 center,float radius,float a_min,float a_max,int num_segments);
extern int GetColumnIndex();
extern void ShowFontSelector(const char* label);
extern void TreePush_Str(const char* str_id);
extern void TreePush_PtrV(const void* ptr_id);
extern ImColor* Color_ImColor_Nil();
extern ImColor* Color_ImColor_Float(float r,float g,float b,float a);
extern ImColor* Color_ImColor_Vec4(const ImVec4 col);
extern ImColor* Color_ImColor_Int(int r,int g,int b,int a);
extern ImColor* Color_ImColor_U32(ImU32 rgba);
extern void DrawCmd_Destroy(ImDrawCmd* self);
extern void FontAtlas_SetTexID(ImFontAtlas* self,ImTextureID id);
extern bool InputTextMultilineV(const char* label,char* buf,size_t buf_size,const ImVec2 size,ImGuiInputTextFlags flags,ImGuiInputTextCallback callback,void* user_data);
extern void LogButtons();
extern void NewLine();
extern void EndMenu();
extern float GetColumnWidthV(int column_index);
extern void DrawList_PrimReserve(ImDrawList* self,int idx_count,int vtx_count);
extern void GetMouseDragDeltaV(ImVec2 *pOut,ImGuiMouseButton button,float lock_threshold);
extern void TableHeadersRow();
extern void TextColored(const ImVec4 col,const char* fmt);
extern void SetNextWindowBgAlpha(float alpha);
extern void EndDragDropTarget();
extern bool IsItemToggledOpen();
extern void* MemAlloc(size_t size);
extern void SaveIniSettingsToDisk(const char* ini_filename);
extern const char* SaveIniSettingsToMemoryV(size_t* out_ini_size);
extern void Payload_Destroy(ImGuiPayload* self);
extern ImGuiID GetWindowDockID();
extern void PopStyleColorV(int count);
extern void TextBuffer_Reserve(ImGuiTextBuffer* self,int capacity);
extern int GetFrameCount();
extern void Context_Destroy(ImGuiContext* self);
extern void BeginTooltip();
extern bool IsMouseHoveringRectV(const ImVec2 r_min,const ImVec2 r_max,bool clip);
extern void SetNextWindowCollapsedV(bool collapsed,ImGuiCond cond);
extern void FontGlyphRangesBuilder_AddTextV(ImFontGlyphRangesBuilder* self,const char* text);
extern bool DragFloat4V(const char* label,float v[4],float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void NextColumn();
extern float GetWindowHeight();
extern void PopFont();
extern void DrawList_PathLineTo(ImDrawList* self,const ImVec2 pos);
extern bool Payload_IsDelivery(ImGuiPayload* self);
extern bool BeginMainMenuBar();
extern void IO_AddMouseButtonEvent(ImGuiIO* self,int button,bool down);
extern void End();
extern bool InputDoubleV(const char* label,double* v,double step,double step_fast,const char* format,ImGuiInputTextFlags flags);
extern bool IsKeyDown(ImGuiKey key);
extern void PushTextWrapPosV(float wrap_local_pos_x);
extern void SetNextWindowViewport(ImGuiID viewport_id);
extern ImGuiOnceUponAFrame* OnceUponAFrame_ImGuiOnceUponAFrame();
extern int GetKeyIndex(ImGuiKey key);
extern void DestroyPlatformWindows();
extern bool DragFloat2V(const char* label,float v[2],float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern ImGuiViewport* FindViewportByPlatformHandle(void* platform_handle);
extern void IO_AddFocusEvent(ImGuiIO* self,bool focused);
extern ImGuiStyle* Style_ImGuiStyle();
extern bool IsKeyPressedV(ImGuiKey key,bool repeat);
extern void LogToFileV(int auto_open_depth,const char* filename);
extern void DrawListSplitter_ClearFreeMemory(ImDrawListSplitter* self);
extern bool BeginMenuBar();
extern void DrawList_PathArcToFast(ImDrawList* self,const ImVec2 center,float radius,int a_min_of_12,int a_max_of_12);
extern bool Font_IsGlyphRangeUnused(ImFont* self,unsigned int c_begin,unsigned int c_last);
extern bool IsItemActivated();
extern bool ColorPicker3V(const char* label,float col[3],ImGuiColorEditFlags flags);
extern bool RadioButton_Bool(const char* label,bool active);
extern bool RadioButton_IntPtr(const char* label,int* v,int v_button);
extern bool IsItemClickedV(ImGuiMouseButton mouse_button);
extern bool IsWindowHoveredV(ImGuiHoveredFlags flags);
extern void NewFrame();
extern ImGuiWindowClass* WindowClass_ImGuiWindowClass();
extern void GetMousePosOnOpeningCurrentPopup(ImVec2 *pOut);
extern void SetNextFrameWantCaptureMouse(bool want_capture_mouse);
extern void FontGlyphRangesBuilder_Destroy(ImFontGlyphRangesBuilder* self);
extern ImGuiMouseCursor GetMouseCursor();
extern void Color_HSVV(ImColor *pOut,float h,float s,float v,float a);
extern void ShowAboutWindowV(bool* p_open);
extern void EndTooltip();
extern bool SliderInt2V(const char* label,int v[2],int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern bool TextFilter_DrawV(ImGuiTextFilter* self,const char* label,float width);
extern void ListClipper_End(ImGuiListClipper* self);
extern bool ImageButtonV(const char* str_id,ImTextureID user_texture_id,const ImVec2 size,const ImVec2 uv0,const ImVec2 uv1,const ImVec4 bg_col,const ImVec4 tint_col);
extern const ImWchar* FontAtlas_GetGlyphRangesChineseSimplifiedCommon(ImFontAtlas* self);
extern ImFontAtlas* FontAtlas_ImFontAtlas();
extern ImGuiViewport* GetWindowViewport();
extern void ListClipperData_Destroy(ImGuiListClipperData* self);
extern ImGuiPlatformMonitor* PlatformMonitor_ImGuiPlatformMonitor();
extern void ColumnsV(int count,const char* id,bool border);
extern void ShowDemoWindowV(bool* p_open);
extern void DrawList_PathStrokeV(ImDrawList* self,ImU32 col,ImDrawFlags flags,float thickness);
extern const ImFontGlyph* Font_FindGlyph(ImFont* self,ImWchar c);
extern void ColorConvertHSVtoRGB(float h,float s,float v,float* out_r,float* out_g,float* out_b);
extern float GetScrollX();
extern void SetScrollY_Float(float scroll_y);
extern bool FontAtlas_GetMouseCursorTexData(ImFontAtlas* self,ImGuiMouseCursor cursor,ImVec2* out_offset,ImVec2* out_size,ImVec2 out_uv_border[2],ImVec2 out_uv_fill[2]);
extern bool BeginMenuV(const char* label,bool enabled);
extern void Payload_Clear(ImGuiPayload* self);
extern bool BeginTabBarV(const char* str_id,ImGuiTabBarFlags flags);
extern void DrawData_ScaleClipRects(ImDrawData* self,const ImVec2 fb_scale);
extern void IO_SetKeyEventNativeDataV(ImGuiIO* self,ImGuiKey key,int native_keycode,int native_scancode,int native_legacy_index);
extern void InputTextCallbackData_InsertCharsV(ImGuiInputTextCallbackData* self,int pos,const char* text);
extern float GetWindowDpiScale();
extern ImDrawData* DrawData_ImDrawData();
extern void GetDrawCursorStartPos(ImVec2 *pOut);
extern void IO_SetAppAcceptingEvents(ImGuiIO* self,bool accepting_events);
extern bool InputTextWithHintV(const char* label,const char* hint,char* buf,size_t buf_size,ImGuiInputTextFlags flags,ImGuiInputTextCallback callback,void* user_data);
extern bool TextFilter_PassFilterV(ImGuiTextFilter* self,const char* text);
extern const char* TextBuffer_c_str(ImGuiTextBuffer* self);
extern void SetNextItemWidth(float item_width);
extern void SetTooltip(const char* fmt);
extern bool IsPopupOpen_StrV(const char* str_id,ImGuiPopupFlags flags);
extern void SetKeyboardFocusHereV(int offset);
extern const ImWchar* FontAtlas_GetGlyphRangesChineseFull(ImFontAtlas* self);
extern void IO_ClearInputKeys(ImGuiIO* self);
extern bool IsItemVisible();
extern void SetNextItemOpenV(bool is_open,ImGuiCond cond);
extern ImGuiTableColumnFlags TableGetColumnFlagsV(int column_n);
extern bool CheckboxFlags_IntPtr(const char* label,int* flags,int flags_value);
extern bool CheckboxFlags_UintPtr(const char* label,unsigned int* flags,unsigned int flags_value);
extern void TableSetColumnEnabled(int column_n,bool v);
extern void DrawList_AddCallback(ImDrawList* self,ImDrawCallback callback,void* callback_data);
extern void SetNextWindowClass(const ImGuiWindowClass* window_class);
extern void DrawList_AddRectV(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col,float rounding,ImDrawFlags flags,float thickness);
extern void MenuColumns_Destroy(ImGuiMenuColumns* self);
extern bool SliderInt3V(const char* label,int v[3],int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void SetColorEditOptions(ImGuiColorEditFlags flags);
extern bool TabItemButtonV(const char* label,ImGuiTabItemFlags flags);
extern const ImWchar* FontAtlas_GetGlyphRangesThai(ImFontAtlas* self);
extern void PushFont(ImFont* font);
extern float GetScrollMaxX();
extern void TableNextRowV(ImGuiTableRowFlags row_flags,float min_row_height);
extern void DrawList_AddTriangleV(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col,float thickness);
extern void OpenPopupOnItemClickV(const char* str_id,ImGuiPopupFlags popup_flags);
extern float CalcItemWidth();
extern int TextBuffer_Size(ImGuiTextBuffer* self);
extern const ImGuiPayload* AcceptDragDropPayloadV(const char* type,ImGuiDragDropFlags flags);
extern bool ArrowButton(const char* str_id,ImGuiDir dir);
extern void DrawList_AddPolyline(ImDrawList* self,const ImVec2* points,int num_points,ImU32 col,ImDrawFlags flags,float thickness);
extern ImDrawList* DrawList_CloneOutput(ImDrawList* self);
extern void PopupData_Destroy(ImGuiPopupData* self);
extern ImGuiTextBuffer* TextBuffer_ImGuiTextBuffer();
extern void GetWindowContentRegionMax(ImVec2 *pOut);
extern bool InputFloatV(const char* label,float* v,float step,float step_fast,const char* format,ImGuiInputTextFlags flags);
extern void DrawList_AddConvexPolyFilled(ImDrawList* self,const ImVec2* points,int num_points,ImU32 col);
extern ImFont* FontAtlas_AddFontFromMemoryTTFV(ImFontAtlas* self,void* font_data,int font_size,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern const char* TextBuffer_Begin(ImGuiTextBuffer* self);
extern void DrawList_AddText_Vec2V(ImDrawList* self,const ImVec2 pos,ImU32 col,const char* text_begin);
extern void DrawList_AddText_FontPtrV(ImDrawList* self,const ImFont* font,float font_size,const ImVec2 pos,ImU32 col,const char* text_begin,float wrap_width,const ImVec4* cpu_fine_clip_rect);
extern void DrawList_PrimUnreserve(ImDrawList* self,int idx_count,int vtx_count);
extern void EndDragDropSource();
extern void NavItemData_Destroy(ImGuiNavItemData* self);
extern bool BeginPopupContextItemV(const char* str_id,ImGuiPopupFlags popup_flags);
extern void OnceUponAFrame_Destroy(ImGuiOnceUponAFrame* self);
extern int GetColumnsCount();
extern ImFont* GetFont();
extern void DrawList_AddNgonV(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments,float thickness);
extern bool FontAtlas_Build(ImFontAtlas* self);
extern void SetColumnOffset(int column_index,float offset_x);
extern void EndChild();
extern void IO_AddMousePosEvent(ImGuiIO* self,float x,float y);
extern void Font_SetGlyphVisible(ImFont* self,ImWchar c,bool visible);
extern void SetNextWindowContentSize(const ImVec2 size);
extern bool DragInt4V(const char* label,int v[4],float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern bool DragIntV(const char* label,int* v,float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void IO_AddMouseViewportEvent(ImGuiIO* self,ImGuiID id);
extern void TextBuffer_Clear(ImGuiTextBuffer* self);
extern bool IsMouseDraggingV(ImGuiMouseButton button,float lock_threshold);
extern void DrawListSplitter_SetCurrentChannel(ImDrawListSplitter* self,ImDrawList* draw_list,int channel_idx);
extern ImGuiPlatformImeData* PlatformImeData_ImGuiPlatformImeData();
extern void TableSetupColumnV(const char* label,ImGuiTableColumnFlags flags,float init_width_or_weight,ImGuiID user_id);
extern bool SliderFloat3V(const char* label,float v[3],float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void FontAtlas_ClearInputData(ImFontAtlas* self);
extern const char* GetVersion();
extern bool IsMousePosValidV(const ImVec2* mouse_pos);
extern bool Selectable_BoolV(const char* label,bool selected,ImGuiSelectableFlags flags,const ImVec2 size);
extern bool Selectable_BoolPtrV(const char* label,bool* p_selected,ImGuiSelectableFlags flags,const ImVec2 size);
extern void TabItem_Destroy(ImGuiTabItem* self);
extern int GetMouseClickedCount(ImGuiMouseButton button);
extern bool SliderScalarNV(const char* label,ImGuiDataType data_type,void* p_data,int components,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern void FontGlyphRangesBuilder_Clear(ImFontGlyphRangesBuilder* self);
extern void Font_RenderChar(ImFont* self,ImDrawList* draw_list,float size,const ImVec2 pos,ImU32 col,ImWchar c);
extern ImGuiIO* IO_ImGuiIO();
extern void GetWindowContentRegionMin(ImVec2 *pOut);
extern ImDrawCmd* DrawCmd_ImDrawCmd();
extern ImFont* FontAtlas_AddFontFromFileTTFV(ImFontAtlas* self,const char* filename,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern void FontAtlas_Destroy(ImFontAtlas* self);
extern int TableGetColumnCount();
extern void Viewport_GetWorkCenter(ImVec2 *pOut,ImGuiViewport* self);
extern void GetMousePos(ImVec2 *pOut);
extern ImGuiTableSortSpecs* TableGetSortSpecs();
extern const ImWchar* FontAtlas_GetGlyphRangesCyrillic(ImFontAtlas* self);
extern void MetricsConfig_Destroy(ImGuiMetricsConfig* self);
extern void GetWindowPos(ImVec2 *pOut);
extern bool FontAtlasCustomRect_IsPacked(ImFontAtlasCustomRect* self);
extern void TextFilter_Build(ImGuiTextFilter* self);
extern void SetItemAllowOverlap();
extern ImGuiPlatformIO* PlatformIO_ImGuiPlatformIO();
extern bool ListClipper_Step(ImGuiListClipper* self);
extern float GetTextLineHeightWithSpacing();
extern void GetDrawCursorScreenPos(ImVec2 *pOut);
extern const ImGuiPayload* GetDragDropPayload();
extern void Color_Destroy(ImColor* self);
extern void EndListBox();
extern bool InputFloat4V(const char* label,float v[4],const char* format,ImGuiInputTextFlags flags);
extern bool InputInt3V(const char* label,int v[3],ImGuiInputTextFlags flags);
extern void DrawList_AddRectFilledV(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col,float rounding,ImDrawFlags flags);
extern void DrawList_PushClipRectV(ImDrawList* self,const ImVec2 clip_rect_min,const ImVec2 clip_rect_max,bool intersect_with_current_clip_rect);
extern bool BeginChildFrameV(ImGuiID id,const ImVec2 size,ImGuiWindowFlags flags);
extern bool ButtonV(const char* label,const ImVec2 size);
extern void DrawList_PrimVtx(ImDrawList* self,const ImVec2 pos,const ImVec2 uv,ImU32 col);
extern bool BeginPopupModalV(const char* name,bool* p_open,ImGuiWindowFlags flags);
extern bool IsWindowAppearing();
extern void SetScrollFromPosY_FloatV(float local_y,float center_y_ratio);
extern ImDrawData* GetDrawData();
extern float GetScrollY();
extern void DrawList_AddQuadV(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col,float thickness);
extern void Style_ScaleAllSizes(ImGuiStyle* self,float scale_factor);
extern void DrawList_PathBezierQuadraticCurveToV(ImDrawList* self,const ImVec2 p2,const ImVec2 p3,int num_segments);
extern bool SliderFloat2V(const char* label,float v[2],float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void FontAtlas_CalcCustomRectUV(ImFontAtlas* self,const ImFontAtlasCustomRect* rect,ImVec2* out_uv_min,ImVec2* out_uv_max);
extern void FontGlyphRangesBuilder_BuildRanges(ImFontGlyphRangesBuilder* self,ImVector_ImWchar* out_ranges);
extern ImGuiListClipper* ListClipper_ImGuiListClipper();
extern bool VSliderScalarV(const char* label,const ImVec2 size,ImGuiDataType data_type,void* p_data,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern void ColorConvertU32ToFloat4(ImVec4 *pOut,ImU32 in);
extern float GetTreeNodeToLabelSpacing();
extern void LastItemData_Destroy(ImGuiLastItemData* self);
extern void EndMenuBar();
extern float GetDrawCursorPosY();
extern bool InputInt4V(const char* label,int v[4],ImGuiInputTextFlags flags);
extern void SetWindowFontScale(float scale);
extern void DrawListSharedData_Destroy(ImDrawListSharedData* self);
extern ImFontAtlasCustomRect* FontAtlasCustomRect_ImFontAtlasCustomRect();
extern ImFontGlyphRangesBuilder* FontGlyphRangesBuilder_ImFontGlyphRangesBuilder();
extern void LogFinish();
extern void StackSizes_Destroy(ImGuiStackSizes* self);
extern ImVec4* Vec4_ImVec4_Nil();
extern ImVec4* Vec4_ImVec4_Float(float _x,float _y,float _z,float _w);
extern void DrawData_Destroy(ImDrawData* self);
extern bool BeginPopupContextWindowV(const char* str_id,ImGuiPopupFlags popup_flags);
extern void DrawData_Clear(ImDrawData* self);
extern void TextWrapped(const char* fmt);
extern const ImWchar* FontAtlas_GetGlyphRangesDefault(ImFontAtlas* self);
extern ImGuiIO* GetIO();
extern void ContextHook_Destroy(ImGuiContextHook* self);
extern const char* GetStyleColorName(ImGuiCol idx);
extern void LogToTTYV(int auto_open_depth);
extern void ProgressBarV(float fraction,const ImVec2 size_arg,const char* overlay);
extern ImDrawListSharedData* GetDrawListSharedData();
extern bool IsMouseReleased(ImGuiMouseButton button);
extern void Spacing();
extern void WindowClass_Destroy(ImGuiWindowClass* self);
extern bool InputTextV(const char* label,char* buf,size_t buf_size,ImGuiInputTextFlags flags,ImGuiInputTextCallback callback,void* user_data);
extern bool BeginDragDropSourceV(ImGuiDragDropFlags flags);
extern bool Checkbox(const char* label,bool* v);
extern bool IsRectVisible_Nil(const ImVec2 size);
extern bool IsRectVisible_Vec2(const ImVec2 rect_min,const ImVec2 rect_max);
extern void DrawList_PopClipRect(ImDrawList* self);
extern const ImWchar* FontAtlas_GetGlyphRangesJapanese(ImFontAtlas* self);
extern void IO_AddKeyAnalogEvent(ImGuiIO* self,ImGuiKey key,bool down,float v);
extern bool TableSetColumnIndex(int column_n);
extern void TableSetupScrollFreeze(int cols,int rows);
extern bool VSliderFloatV(const char* label,const ImVec2 size,float* v,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void IO_ClearInputCharacters(ImGuiIO* self);
extern float GetFrameHeightWithSpacing();
extern bool TextBuffer_Empty(ImGuiTextBuffer* self);
extern void StyleMod_Destroy(ImGuiStyleMod* self);
extern void RenderPlatformWindowsDefaultV(void* platform_render_arg,void* renderer_render_arg);
extern void DrawList_AddBezierCubicV(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col,float thickness,int num_segments);
extern void PlatformMonitor_Destroy(ImGuiPlatformMonitor* self);
extern void Separator();
extern int TableGetColumnIndex();
extern float Font_GetCharAdvance(ImFont* self,ImWchar c);
extern bool DragFloatV(const char* label,float* v,float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void Vec4_Destroy(ImVec4* self);
extern void PopTextWrapPos();
extern void DrawList_PushClipRectFullScreen(ImDrawList* self);
extern const char* Font_GetDebugName(ImFont* self);
extern void TextDisabled(const char* fmt);
extern void StyleColorsClassicV(ImGuiStyle* dst);
extern bool VSliderIntV(const char* label,const ImVec2 size,int* v,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void Font_RenderTextV(ImFont* self,ImDrawList* draw_list,float size,const ImVec2 pos,ImU32 col,const ImVec4 clip_rect,const char* text_begin,float wrap_width,bool cpu_fine_clip);
extern void SetDrawCursorPos(const ImVec2 local_pos);
extern bool BeginPopupV(const char* str_id,ImGuiWindowFlags flags);
extern float GetFrameHeight();
extern void DrawList_GetClipRectMax(ImVec2 *pOut,ImDrawList* self);
extern void EndMainMenuBar();
extern int TableGetRowIndex();
extern void DockContext_Destroy(ImGuiDockContext* self);
extern void NextItemData_Destroy(ImGuiNextItemData* self);
extern void EndCombo();
extern void SetScrollHereYV(float center_y_ratio);
extern bool IsItemDeactivated();
extern bool SliderScalarV(const char* label,ImGuiDataType data_type,void* p_data,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern void DrawList_AddRectFilledMultiColor(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col_upr_left,ImU32 col_upr_right,ImU32 col_bot_right,ImU32 col_bot_left);
extern void DrawList_PushTextureID(ImDrawList* self,ImTextureID texture_id);
extern const char* TableGetColumnName_IntV(int column_n);
extern bool ColorButtonV(const char* desc_id,const ImVec4 col,ImGuiColorEditFlags flags,const ImVec2 size);
extern bool DragIntRange2V(const char* label,int* v_current_min,int* v_current_max,float v_speed,int v_min,int v_max,const char* format,const char* format_max,ImGuiSliderFlags flags);
extern void DrawList_PathBezierCubicCurveToV(ImDrawList* self,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,int num_segments);
extern bool InputInt2V(const char* label,int v[2],ImGuiInputTextFlags flags);
extern void BeginGroup();
extern bool BeginListBoxV(const char* label,const ImVec2 size);
extern bool IsMouseDown(ImGuiMouseButton button);
extern bool IsAnyItemActive();
extern void DrawList_PathLineToMergeDuplicate(ImDrawList* self,const ImVec2 pos);
extern ImGuiContext* GetCurrentContext();
extern bool IsAnyMouseDown();
extern void DrawList_PathClear(ImDrawList* self);
extern void SetNextWindowSizeV(const ImVec2 size,ImGuiCond cond);
extern void DestroyContextV(ImGuiContext* ctx);
extern void DrawList_PrimWriteVtx(ImDrawList* self,const ImVec2 pos,const ImVec2 uv,ImU32 col);
extern bool IsAnyItemHovered();
extern bool SliderFloat4V(const char* label,float v[4],float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void DrawList_GetClipRectMin(ImVec2 *pOut,ImDrawList* self);
extern void PushAllowKeyboardFocus(bool allow_keyboard_focus);
extern void DrawData_DeIndexAllBuffers(ImDrawData* self);
extern const char* Font_CalcWordWrapPositionA(ImFont* self,float scale,const char* text,float wrap_width);
extern void SetScrollHereXV(float center_x_ratio);
extern void DrawList_AddQuadFilled(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col);
extern void TableColumnSettings_Destroy(ImGuiTableColumnSettings* self);
extern ImTextureID DrawCmd_GetTexID(ImDrawCmd* self);
extern void TextFilter_Destroy(ImGuiTextFilter* self);
extern void TextBuffer_Destroy(ImGuiTextBuffer* self);
extern ImGuiTableSortSpecs* TableSortSpecs_ImGuiTableSortSpecs();
extern void EndDisabled();
extern bool SliderFloatV(const char* label,float* v,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void DrawList_PrimRect(ImDrawList* self,const ImVec2 a,const ImVec2 b,ImU32 col);
extern void FontConfig_Destroy(ImFontConfig* self);
extern ImFont* Font_ImFont();
extern void ShowStyleEditorV(ImGuiStyle* ref);
extern void Dummy(const ImVec2 size);
extern void ResetMouseDragDeltaV(ImGuiMouseButton button);
extern void SetNextWindowPosV(const ImVec2 pos,ImGuiCond cond,const ImVec2 pivot);
extern bool ColorEdit4V(const char* label,float col[4],ImGuiColorEditFlags flags);
extern bool IsWindowCollapsed();
extern void DrawListSplitter_Merge(ImDrawListSplitter* self,ImDrawList* draw_list);
extern void FontAtlas_Clear(ImFontAtlas* self);
extern void WindowSettings_Destroy(ImGuiWindowSettings* self);
extern bool SliderInt4V(const char* label,int v[4],int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void PlatformImeData_Destroy(ImGuiPlatformImeData* self);
extern bool DragScalarV(const char* label,ImGuiDataType data_type,void* p_data,float v_speed,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern bool BeginComboV(const char* label,const char* preview_value,ImGuiComboFlags flags);
extern void OpenPopup_StrV(const char* str_id,ImGuiPopupFlags popup_flags);
extern void OpenPopup_IDV(ImGuiID id,ImGuiPopupFlags popup_flags);
extern bool Font_IsLoaded(ImFont* self);
extern ImGuiPayload* Payload_ImGuiPayload();
extern void SetScrollX_Float(float scroll_x);
extern float GetDrawCursorPosX();
extern bool SetDragDropPayloadV(const char* type,const void* data,size_t sz,ImGuiCond cond);
extern void ImageV(ImTextureID user_texture_id,const ImVec2 size,const ImVec2 uv0,const ImVec2 uv1,const ImVec4 tint_col,const ImVec4 border_col);
extern void InputEvent_Destroy(ImGuiInputEvent* self);
extern void TextBuffer_Appendf(ImGuiTextBuffer* self,const char* fmt);
extern void IO_AddInputCharacterUTF16(ImGuiIO* self,ImWchar16 c);
extern void PushButtonRepeat(bool repeat);
extern void InputTextCallbackData_SelectAll(ImGuiInputTextCallbackData* self);
extern void Font_AddGlyph(ImFont* self,const ImFontConfig* src_cfg,ImWchar c,float x0,float y0,float x1,float y1,float u0,float v0,float u1,float v1,float advance_x);
extern void CloseCurrentPopup();
extern ImU32 GetColorU32_ColV(ImGuiCol idx,float alpha_mul);
extern ImU32 GetColorU32_Vec4(const ImVec4 col);
extern ImU32 GetColorU32_U32(ImU32 col);
extern ImFont* FontAtlas_AddFontDefaultV(ImFontAtlas* self,const ImFontConfig* font_cfg);
extern void ListClipper_Destroy(ImGuiListClipper* self);
extern bool Combo_Str_arrV(const char* label,int* current_item,const char* const items[],int items_count,int popup_max_height_in_items);
extern bool Combo_StrV(const char* label,int* current_item,const char* items_separated_by_zeros,int popup_max_height_in_items);
extern bool Combo_FnBoolPtr(const char* label,int* current_item,bool(*items_getter)(void* data,int idx,const char** out_text),void* data,int items_count,int popup_max_height_in_items);
extern void SetItemDefaultFocus();
extern void DrawList_AddCircleV(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments,float thickness);
extern void FontAtlas_ClearFonts(ImFontAtlas* self);
extern bool BeginV(const char* name,bool* p_open,ImGuiWindowFlags flags);
extern void Font_Destroy(ImFont* self);
extern void BeginDisabledV(bool disabled);
extern void DrawListSplitter_Split(ImDrawListSplitter* self,ImDrawList* draw_list,int count);
extern ImDrawList* DrawList_ImDrawList(const ImDrawListSharedData* shared_data);
extern void ShowUserGuide();
extern void OldColumns_Destroy(ImGuiOldColumns* self);
extern void LoadIniSettingsFromDisk(const char* ini_filename);
extern int FontAtlas_AddCustomRectRegular(ImFontAtlas* self,int width,int height);
extern bool FontAtlas_IsBuilt(ImFontAtlas* self);
extern void GetDrawCursorPos(ImVec2 *pOut);
extern double GetTime();
extern void Font_ClearOutputData(ImFont* self);
extern ImGuiContext* CreateContextV(ImFontAtlas* shared_font_atlas);
extern bool IsMouseClickedV(ImGuiMouseButton button,bool repeat);
extern void AlignTextToFramePadding();
extern void DrawList_ChannelsMerge(ImDrawList* self);
extern void TabBar_Destroy(ImGuiTabBar* self);
extern void SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard);
extern const ImWchar* FontAtlas_GetGlyphRangesKorean(ImFontAtlas* self);
extern ImGuiViewport* Viewport_ImGuiViewport();
extern bool TreeNodeEx_StrV(const char* label,ImGuiTreeNodeFlags flags);
extern bool TreeNodeEx_StrStr(const char* str_id,ImGuiTreeNodeFlags flags,const char* fmt);
extern bool TreeNodeEx_Ptr(const void* ptr_id,ImGuiTreeNodeFlags flags,const char* fmt);
extern void DrawListSplitter_Clear(ImDrawListSplitter* self);
extern bool ShowStyleSelector(const char* label);
extern void LoadIniSettingsFromMemoryV(const char* ini_data,size_t ini_size);
extern void Rect_Destroy(ImRect* self);
extern bool BeginDragDropTarget();
extern bool InputIntV(const char* label,int* v,int step,int step_fast,ImGuiInputTextFlags flags);
extern bool IsKeyReleased(ImGuiKey key);
extern bool IsWindowDocked();
extern void ListClipper_ForceDisplayRangeByIndices(ImGuiListClipper* self,int item_min,int item_max);
extern float GetColumnOffsetV(int column_index);
extern void SetNextWindowDockIDV(ImGuiID dock_id,ImGuiCond cond);
extern void DrawList_AddCircleFilledV(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments);
extern void IO_AddKeyEvent(ImGuiIO* self,ImGuiKey key,bool down);
extern void GetItemRectMin(ImVec2 *pOut);
extern void Viewport_GetCenter(ImVec2 *pOut,ImGuiViewport* self);
extern void ShowStackToolWindowV(bool* p_open);
extern ImFont* FontAtlas_AddFontFromMemoryCompressedBase85TTFV(ImFontAtlas* self,const char* compressed_font_data_base85,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern void SettingsHandler_Destroy(ImGuiSettingsHandler* self);
extern void InputTextCallbackData_Destroy(ImGuiInputTextCallbackData* self);
extern bool InputTextCallbackData_HasSelection(ImGuiInputTextCallbackData* self);
extern void EndTabBar();
extern float GetFontSize();
extern bool ColorPicker4V(const char* label,float col[4],ImGuiColorEditFlags flags,const float* ref_col);
extern void TreePop();
extern void SetWindowFocus_Nil();
extern void SetWindowFocus_Str(const char* name);
extern void EndTable();
extern void GetContentRegionAvail(ImVec2 *pOut);
extern bool IsWindowFocusedV(ImGuiFocusedFlags flags);
extern void IO_AddInputCharactersUTF8(ImGuiIO* self,const char* str);
extern void PopClipRect();
extern void StyleColorsDarkV(ImGuiStyle* dst);
extern void TableInstanceData_Destroy(ImGuiTableInstanceData* self);
extern bool IsItemDeactivatedAfterEdit();
extern void GetFontTexUvWhitePixel(ImVec2 *pOut);
extern bool TreeNode_Str(const char* label);
extern bool TreeNode_StrStr(const char* str_id,const char* fmt);
extern bool TreeNode_Ptr(const void* ptr_id,const char* fmt);
extern void DrawList_PrimWriteIdx(ImDrawList* self,ImDrawIdx idx);
extern ImFontConfig* FontConfig_ImFontConfig();
extern bool CollapsingHeader_TreeNodeFlagsV(const char* label,ImGuiTreeNodeFlags flags);
extern bool CollapsingHeader_BoolPtrV(const char* label,bool* p_visible,ImGuiTreeNodeFlags flags);
extern void DrawList_AddTriangleFilled(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col);
extern int FontAtlas_AddCustomRectFontGlyphV(ImFontAtlas* self,ImFont* font,ImWchar id,int width,int height,float advance_x,const ImVec2 offset);
extern void TableSetBgColorV(ImGuiTableBgTarget target,ImU32 color,int column_n);
extern void DrawListSplitter_Destroy(ImDrawListSplitter* self);
extern void SetNextWindowFocus();
extern void SetWindowCollapsed_BoolV(bool collapsed,ImGuiCond cond);
extern void SetWindowCollapsed_StrV(const char* name,bool collapsed,ImGuiCond cond);
extern bool IsItemFocused();
extern void PlotHistogram_FloatPtrV(const char* label,const float* values,int values_count,int values_offset,const char* overlay_text,float scale_min,float scale_max,ImVec2 graph_size,int stride);
extern void PlotHistogram_FnFloatPtr(const char* label,float(*values_getter)(void* data,int idx),void* data,int values_count,int values_offset,const char* overlay_text,float scale_min,float scale_max,ImVec2 graph_size);
extern bool DragFloatRange2V(const char* label,float* v_current_min,float* v_current_max,float v_speed,float v_min,float v_max,const char* format,const char* format_max,ImGuiSliderFlags flags);
extern float GetTextLineHeight();
extern void TableSortSpecs_Destroy(ImGuiTableSortSpecs* self);
extern void TextFilter_Clear(ImGuiTextFilter* self);
extern void GetContentRegionMax(ImVec2 *pOut);
extern void PopStyleVarV(int count);
extern void PopButtonRepeat();
extern void PopItemWidth();
extern void InputTextState_Destroy(ImGuiInputTextState* self);
extern void PlatformIO_Destroy(ImGuiPlatformIO* self);
extern bool InputFloat3V(const char* label,float v[3],const char* format,ImGuiInputTextFlags flags);
extern void FontGlyphRangesBuilder_AddChar(ImFontGlyphRangesBuilder* self,ImWchar c);
extern bool BeginTabItemV(const char* label,bool* p_open,ImGuiTabItemFlags flags);
extern void Vec1_Destroy(ImVec1* self);
extern bool InputScalarNV(const char* label,ImGuiDataType data_type,void* p_data,int components,const void* p_step,const void* p_step_fast,const char* format,ImGuiInputTextFlags flags);
extern bool MenuItem_BoolV(const char* label,const char* shortcut,bool selected,bool enabled);
extern bool MenuItem_BoolPtrV(const char* label,const char* shortcut,bool* p_selected,bool enabled);
extern void PushStyleVar_Float(ImGuiStyleVar idx,float val);
extern void PushStyleVar_Vec2(ImGuiStyleVar idx,const ImVec2 val);
extern void DrawList_PrimRectUV(ImDrawList* self,const ImVec2 a,const ImVec2 b,const ImVec2 uv_a,const ImVec2 uv_b,ImU32 col);
extern void FontAtlas_GetTexDataAsRGBA32V(ImFontAtlas* self,unsigned char** out_pixels,int* out_width,int* out_height,int* out_bytes_per_pixel);
extern void StackTool_Destroy(ImGuiStackTool* self);
extern void SetColumnWidth(int column_index,float width);
extern void SetScrollFromPosX_FloatV(float local_x,float center_x_ratio);
extern void EndGroup();
extern float GetScrollMaxY();
extern void DrawList_ChannelsSetCurrent(ImDrawList* self,int n);
extern ImGuiTextFilter* TextFilter_ImGuiTextFilter(const char* default_filter);
extern ImGuiPlatformIO* GetPlatformIO();
extern void TableHeader(const char* label);
extern void IO_AddMouseWheelEvent(ImGuiIO* self,float wh_x,float wh_y);
extern void DrawList_AddImageRoundedV(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p_min,const ImVec2 p_max,const ImVec2 uv_min,const ImVec2 uv_max,ImU32 col,float rounding,ImDrawFlags flags);
extern void ComboPreviewData_Destroy(ImGuiComboPreviewData* self);
extern void OldColumnData_Destroy(ImGuiOldColumnData* self);
extern void ColorConvertRGBtoHSV(float r,float g,float b,float* out_h,float* out_s,float* out_v);
extern void DrawList_ChannelsSplit(ImDrawList* self,int count);
extern void SetTabItemClosed(const char* tab_or_docked_window_label);
extern void ShowDebugLogWindowV(bool* p_open);
extern void Font_BuildLookupTable(ImFont* self);
extern void Bullet();
extern void LogToClipboardV(int auto_open_depth);
extern void SetCurrentContext(ImGuiContext* ctx);
extern void SetDrawCursorPosY(float local_y);
extern void DrawList_AddDrawCmd(ImDrawList* self);
extern ImVec2* Vec2_ImVec2_Nil();
extern ImVec2* Vec2_ImVec2_Float(float _x,float _y);
extern void BulletText(const char* fmt);
extern bool SliderIntV(const char* label,int* v,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern bool DragInt2V(const char* label,int v[2],float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern bool ListBox_Str_arrV(const char* label,int* current_item,const char* const items[],int items_count,int height_in_items);
extern bool ListBox_FnBoolPtr(const char* label,int* current_item,bool(*items_getter)(void* data,int idx,const char** out_text),void* data,int items_count,int height_in_items);
extern void DrawList_PrimQuadUV(ImDrawList* self,const ImVec2 a,const ImVec2 b,const ImVec2 c,const ImVec2 d,const ImVec2 uv_a,const ImVec2 uv_b,const ImVec2 uv_c,const ImVec2 uv_d,ImU32 col);
extern void SetDrawCursorScreenPos(const ImVec2 pos);
extern void PushClipRect(const ImVec2 clip_rect_min,const ImVec2 clip_rect_max,bool intersect_with_current_clip_rect);
extern void UnindentV(float indent_w);
extern void Color_SetHSVV(ImColor* self,float h,float s,float v,float a);
extern void TableColumnSortSpecs_Destroy(ImGuiTableColumnSortSpecs* self);
extern void DrawList_AddImageQuadV(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,const ImVec2 uv1,const ImVec2 uv2,const ImVec2 uv3,const ImVec2 uv4,ImU32 col);
extern void DrawList_Destroy(ImDrawList* self);
extern const ImVec4* GetStyleColorVec4(ImGuiCol idx);
extern bool BeginPopupContextVoidV(const char* str_id,ImGuiPopupFlags popup_flags);
extern ImU32 ColorConvertFloat4ToU32(const ImVec4 in);
extern bool IsAnyItemFocused();
extern void PushID_Str(const char* str_id);
extern void PushID_StrStr(const char* str_id_begin,const char* str_id_end);
extern void PushID_Ptr(const void* ptr_id);
extern void PushID_Int(int int_id);
extern void DrawList_PathRectV(ImDrawList* self,const ImVec2 rect_min,const ImVec2 rect_max,float rounding,ImDrawFlags flags);
extern ImGuiViewport* FindViewportByID(ImGuiID id);
extern ImDrawList* GetBackgroundDrawList_Nil();
extern ImDrawList* GetBackgroundDrawList_ViewportPtr(ImGuiViewport* viewport);
extern ImDrawList* GetForegroundDrawList_Nil();
extern ImDrawList* GetForegroundDrawList_ViewportPtr(ImGuiViewport* viewport);
extern void GetItemRectSize(ImVec2 *pOut);
extern void PlotLines_FloatPtrV(const char* label,const float* values,int values_count,int values_offset,const char* overlay_text,float scale_min,float scale_max,ImVec2 graph_size,int stride);
extern void PlotLines_FnFloatPtr(const char* label,float(*values_getter)(void* data,int idx),void* data,int values_count,int values_offset,const char* overlay_text,float scale_min,float scale_max,ImVec2 graph_size);
extern void InputTextCallbackData_ClearSelection(ImGuiInputTextCallbackData* self);
extern bool BeginChild_StrV(const char* str_id,const ImVec2 size,bool border,ImGuiWindowFlags flags);
extern bool BeginChild_IDV(ImGuiID id,const ImVec2 size,bool border,ImGuiWindowFlags flags);
extern void PopID();
extern bool SmallButton(const char* label);
extern void EndChildFrame();
extern void Vec2_Destroy(ImVec2* self);
extern void LogText(const char* fmt);
extern void SetWindowSize_Vec2V(const ImVec2 size,ImGuiCond cond);
extern void SetWindowSize_StrV(const char* name,const ImVec2 size,ImGuiCond cond);
extern bool InputFloat2V(const char* label,float v[2],const char* format,ImGuiInputTextFlags flags);
extern void SetDrawCursorPosX(float local_x);
extern void Style_Destroy(ImGuiStyle* self);
extern bool BeginTableV(const char* str_id,int column,ImGuiTableFlags flags,const ImVec2 outer_size,float inner_width);
extern void GetWindowSize(ImVec2 *pOut);
extern void PushStyleColor_U32(ImGuiCol idx,ImU32 col);
extern void PushStyleColor_Vec4(ImGuiCol idx,const ImVec4 col);
extern void DrawList_AddBezierQuadraticV(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col,float thickness,int num_segments);
extern void FontGlyphRangesBuilder_AddRanges(ImFontGlyphRangesBuilder* self,const ImWchar* ranges);
extern ImGuiTableColumnSortSpecs* TableColumnSortSpecs_ImGuiTableColumnSortSpecs();
extern const char* TextBuffer_End(ImGuiTextBuffer* self);
extern void SetNextWindowSizeConstraintsV(const ImVec2 size_min,const ImVec2 size_max,ImGuiSizeCallback custom_callback,void* custom_callback_data);
extern void DrawList_PopTextureID(ImDrawList* self);
extern bool FontGlyphRangesBuilder_GetBit(ImFontGlyphRangesBuilder* self,size_t n);
extern void Font_CalcTextSizeAV(ImVec2 *pOut,ImFont* self,float size,float max_width,float wrap_width,const char* text_begin,const char** remaining);
extern ImGuiStyle* GetStyle();
extern const ImWchar* FontAtlas_GetGlyphRangesVietnamese(ImFontAtlas* self);
extern void FontAtlasCustomRect_Destroy(ImFontAtlasCustomRect* self);
extern void InputTextCallbackData_DeleteChars(ImGuiInputTextCallbackData* self,int pos,int bytes_count);
extern bool DragScalarNV(const char* label,ImGuiDataType data_type,void* p_data,int components,float v_speed,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern ImGuiViewport* GetMainViewport();
extern bool Payload_IsDataType(ImGuiPayload* self,const char* type);
extern void Vec2ih_Destroy(ImVec2ih* self);
extern void IndentV(float indent_w);
extern void PopAllowKeyboardFocus();
extern ImDrawList* GetWindowDrawList();
extern void LabelText(const char* label,const char* fmt);
extern int GetKeyPressedAmount(ImGuiKey key,float repeat_delay,float rate);
extern bool DragFloat3V(const char* label,float v[3],float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void EndPopup();
extern ImDrawListSplitter* DrawListSplitter_ImDrawListSplitter();
extern void Viewport_Destroy(ImGuiViewport* self);
extern void PtrOrIndex_Destroy(ImGuiPtrOrIndex* self);
extern void StackLevelInfo_Destroy(ImGuiStackLevelInfo* self);
extern bool TextFilter_IsActive(ImGuiTextFilter* self);
extern bool IsItemHoveredV(ImGuiHoveredFlags flags);
extern void Render();
extern void TextUnformattedV(const char* text);
extern ImGuiID DockSpaceOverViewportV(const ImGuiViewport* viewport,ImGuiDockNodeFlags flags,const ImGuiWindowClass* window_class);
extern bool DragInt3(const char* label,int v[3]);
extern void Font_AddRemapChar(ImFont* self,ImWchar dst,ImWchar src);
extern bool ColorEdit3(const char* label,float col[3]);
extern ImGuiID DockSpace(ImGuiID id);
extern void ShowMetricsWindow();
extern void SameLine();
extern void DrawList_AddImage(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p_min,const ImVec2 p_max);
extern void CalcTextSize(ImVec2* pOut,const char* text);
extern void TextBuffer_Append(ImGuiTextBuffer* self,const char* str);
extern void SetWindowPos_Vec2(const ImVec2 pos);
extern void SetWindowPos_Str(const char* name,const ImVec2 pos);
extern void ListClipper_Begin(ImGuiListClipper* self,int items_count);
extern void Value_Float(const char* prefix,float v);
extern bool InvisibleButton(const char* str_id,const ImVec2 size);
extern void DrawList_AddLine(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,ImU32 col);
extern ImFont* FontAtlas_AddFontFromMemoryCompressedTTF(ImFontAtlas* self,const void* compressed_font_data,int compressed_font_size,float size_pixels);
extern bool InputScalar(const char* label,ImGuiDataType data_type,void* p_data);
extern void FontAtlas_GetTexDataAsAlpha8(ImFontAtlas* self,unsigned char** out_pixels,int* out_width,int* out_height);
extern void StyleColorsLight();
extern bool SliderAngle(const char* label,float* v_rad);
extern void DrawList_PathArcTo(ImDrawList* self,const ImVec2 center,float radius,float a_min,float a_max);
extern void TreePush_Ptr();
extern bool InputTextMultiline(const char* label,char* buf,size_t buf_size);
extern float GetColumnWidth();
extern void GetMouseDragDelta(ImVec2* pOut);
extern const char* SaveIniSettingsToMemory();
extern void PopStyleColor();
extern bool IsMouseHoveringRect(const ImVec2 r_min,const ImVec2 r_max);
extern void SetNextWindowCollapsed(bool collapsed);
extern void FontGlyphRangesBuilder_AddText(ImFontGlyphRangesBuilder* self,const char* text);
extern bool DragFloat4(const char* label,float v[4]);
extern bool InputDouble(const char* label,double* v);
extern void PushTextWrapPos();
extern bool DragFloat2(const char* label,float v[2]);
extern bool IsKeyPressed(ImGuiKey key);
extern void LogToFile();
extern bool ColorPicker3(const char* label,float col[3]);
extern bool IsItemClicked();
extern bool IsWindowHovered();
extern void Color_HSV(ImColor* pOut,float h,float s,float v);
extern void ShowAboutWindow();
extern bool SliderInt2(const char* label,int v[2],int v_min,int v_max);
extern bool TextFilter_Draw(ImGuiTextFilter* self);
extern void Columns();
extern void ShowDemoWindow();
extern void DrawList_PathStroke(ImDrawList* self,ImU32 col);
extern bool BeginMenu(const char* label);
extern bool BeginTabBar(const char* str_id);
extern void IO_SetKeyEventNativeData(ImGuiIO* self,ImGuiKey key,int native_keycode,int native_scancode);
extern void InputTextCallbackData_InsertChars(ImGuiInputTextCallbackData* self,int pos,const char* text);
extern bool InputTextWithHint(const char* label,const char* hint,char* buf,size_t buf_size);
extern bool TextFilter_PassFilter(ImGuiTextFilter* self,const char* text);
extern bool IsPopupOpen_Str(const char* str_id);
extern void SetKeyboardFocusHere();
extern void SetNextItemOpen(bool is_open);
extern ImGuiTableColumnFlags TableGetColumnFlags();
extern void DrawList_AddRect(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col);
extern bool SliderInt3(const char* label,int v[3],int v_min,int v_max);
extern bool TabItemButton(const char* label);
extern void TableNextRow();
extern void DrawList_AddTriangle(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col);
extern void OpenPopupOnItemClick();
extern const ImGuiPayload* AcceptDragDropPayload(const char* type);
extern bool InputFloat(const char* label,float* v);
extern ImFont* FontAtlas_AddFontFromMemoryTTF(ImFontAtlas* self,void* font_data,int font_size,float size_pixels);
extern void DrawList_AddText_Vec2(ImDrawList* self,const ImVec2 pos,ImU32 col,const char* text_begin);
extern void DrawList_AddText_FontPtr(ImDrawList* self,const ImFont* font,float font_size,const ImVec2 pos,ImU32 col,const char* text_begin);
extern bool BeginPopupContextItem();
extern void DrawList_AddNgon(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments);
extern bool DragInt4(const char* label,int v[4]);
extern bool DragInt(const char* label,int* v);
extern bool IsMouseDragging(ImGuiMouseButton button);
extern void TableSetupColumn(const char* label);
extern bool SliderFloat3(const char* label,float v[3],float v_min,float v_max);
extern bool IsMousePosValid();
extern bool Selectable_Bool(const char* label);
extern bool Selectable_BoolPtr(const char* label,bool* p_selected);
extern bool SliderScalarN(const char* label,ImGuiDataType data_type,void* p_data,int components,const void* p_min,const void* p_max);
extern ImFont* FontAtlas_AddFontFromFileTTF(ImFontAtlas* self,const char* filename,float size_pixels);
extern bool InputFloat4(const char* label,float v[4]);
extern bool InputInt3(const char* label,int v[3]);
extern void DrawList_AddRectFilled(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col);
extern void DrawList_PushClipRect(ImDrawList* self,const ImVec2 clip_rect_min,const ImVec2 clip_rect_max);
extern bool BeginChildFrame(ImGuiID id,const ImVec2 size);
extern bool Button(const char* label);
extern bool BeginPopupModal(const char* name);
extern void SetScrollFromPosY_Float(float local_y);
extern void DrawList_AddQuad(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col);
extern void DrawList_PathBezierQuadraticCurveTo(ImDrawList* self,const ImVec2 p2,const ImVec2 p3);
extern bool SliderFloat2(const char* label,float v[2],float v_min,float v_max);
extern bool VSliderScalar(const char* label,const ImVec2 size,ImGuiDataType data_type,void* p_data,const void* p_min,const void* p_max);
extern bool InputInt4(const char* label,int v[4]);
extern bool BeginPopupContextWindow();
extern void LogToTTY();
extern void ProgressBar(float fraction);
extern bool InputText(const char* label,char* buf,size_t buf_size);
extern bool BeginDragDropSource();
extern bool VSliderFloat(const char* label,const ImVec2 size,float* v,float v_min,float v_max);
extern void RenderPlatformWindowsDefault();
extern void DrawList_AddBezierCubic(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col,float thickness);
extern bool DragFloat(const char* label,float* v);
extern void StyleColorsClassic();
extern bool VSliderInt(const char* label,const ImVec2 size,int* v,int v_min,int v_max);
extern void Font_RenderText(ImFont* self,ImDrawList* draw_list,float size,const ImVec2 pos,ImU32 col,const ImVec4 clip_rect,const char* text_begin);
extern bool BeginPopup(const char* str_id);
extern void SetScrollHereY();
extern bool SliderScalar(const char* label,ImGuiDataType data_type,void* p_data,const void* p_min,const void* p_max);
extern const char* TableGetColumnName_Int();
extern bool ColorButton(const char* desc_id,const ImVec4 col);
extern bool DragIntRange2(const char* label,int* v_current_min,int* v_current_max);
extern void DrawList_PathBezierCubicCurveTo(ImDrawList* self,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4);
extern bool InputInt2(const char* label,int v[2]);
extern bool BeginListBox(const char* label);
extern void SetNextWindowSize(const ImVec2 size);
extern void DestroyContext();
extern bool SliderFloat4(const char* label,float v[4],float v_min,float v_max);
extern void SetScrollHereX();
extern bool SliderFloat(const char* label,float* v,float v_min,float v_max);
extern void ShowStyleEditor();
extern void ResetMouseDragDelta();
extern void SetNextWindowPos(const ImVec2 pos);
extern bool ColorEdit4(const char* label,float col[4]);
extern bool SliderInt4(const char* label,int v[4],int v_min,int v_max);
extern bool DragScalar(const char* label,ImGuiDataType data_type,void* p_data);
extern bool BeginCombo(const char* label,const char* preview_value);
extern void OpenPopup_Str(const char* str_id);
extern void OpenPopup_ID(ImGuiID id);
extern bool SetDragDropPayload(const char* type,const void* data,size_t sz);
extern ImU32 GetColorU32_Col(ImGuiCol idx);
extern ImFont* FontAtlas_AddFontDefault(ImFontAtlas* self);
extern bool Combo_Str_arr(const char* label,int* current_item,const char* const items[],int items_count);
extern bool Combo_Str(const char* label,int* current_item,const char* items_separated_by_zeros);
extern void DrawList_AddCircle(ImDrawList* self,const ImVec2 center,float radius,ImU32 col);
extern bool Begin(const char* name);
extern void BeginDisabled();
extern ImGuiContext* CreateContext();
extern bool IsMouseClicked(ImGuiMouseButton button);
extern bool TreeNodeEx_Str(const char* label);
extern void LoadIniSettingsFromMemory(const char* ini_data);
extern bool InputInt(const char* label,int* v);
extern float GetColumnOffset();
extern void SetNextWindowDockID(ImGuiID dock_id);
extern void DrawList_AddCircleFilled(ImDrawList* self,const ImVec2 center,float radius,ImU32 col);
extern void ShowStackToolWindow();
extern ImFont* FontAtlas_AddFontFromMemoryCompressedBase85TTF(ImFontAtlas* self,const char* compressed_font_data_base85,float size_pixels);
extern bool ColorPicker4(const char* label,float col[4]);
extern bool IsWindowFocused();
extern void StyleColorsDark();
extern bool CollapsingHeader_TreeNodeFlags(const char* label);
extern bool CollapsingHeader_BoolPtr(const char* label,bool* p_visible);
extern int FontAtlas_AddCustomRectFontGlyph(ImFontAtlas* self,ImFont* font,ImWchar id,int width,int height,float advance_x);
extern void TableSetBgColor(ImGuiTableBgTarget target,ImU32 color);
extern void SetWindowCollapsed_Bool(bool collapsed);
extern void SetWindowCollapsed_Str(const char* name,bool collapsed);
extern void PlotHistogram_FloatPtr(const char* label,const float* values,int values_count);
extern bool DragFloatRange2(const char* label,float* v_current_min,float* v_current_max);
extern void PopStyleVar();
extern bool InputFloat3(const char* label,float v[3]);
extern bool BeginTabItem(const char* label);
extern bool InputScalarN(const char* label,ImGuiDataType data_type,void* p_data,int components);
extern bool MenuItem_Bool(const char* label);
extern bool MenuItem_BoolPtr(const char* label,const char* shortcut,bool* p_selected);
extern void FontAtlas_GetTexDataAsRGBA32(ImFontAtlas* self,unsigned char** out_pixels,int* out_width,int* out_height);
extern void SetScrollFromPosX_Float(float local_x);
extern void DrawList_AddImageRounded(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p_min,const ImVec2 p_max,const ImVec2 uv_min,const ImVec2 uv_max,ImU32 col,float rounding);
extern void ShowDebugLogWindow();
extern void LogToClipboard();
extern bool SliderInt(const char* label,int* v,int v_min,int v_max);
extern bool DragInt2(const char* label,int v[2]);
extern bool ListBox_Str_arr(const char* label,int* current_item,const char* const items[],int items_count);
extern void Unindent();
extern void Color_SetHSV(ImColor* self,float h,float s,float v);
extern void DrawList_AddImageQuad(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4);
extern bool BeginPopupContextVoid();
extern void DrawList_PathRect(ImDrawList* self,const ImVec2 rect_min,const ImVec2 rect_max);
extern void PlotLines_FloatPtr(const char* label,const float* values,int values_count);
extern bool BeginChild_Str(const char* str_id);
extern bool BeginChild_ID(ImGuiID id);
extern void SetWindowSize_Vec2(const ImVec2 size);
extern void SetWindowSize_Str(const char* name,const ImVec2 size);
extern bool InputFloat2(const char* label,float v[2]);
extern bool BeginTable(const char* str_id,int column);
extern void DrawList_AddBezierQuadratic(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col,float thickness);
extern void SetNextWindowSizeConstraints(const ImVec2 size_min,const ImVec2 size_max);
extern void Font_CalcTextSizeA(ImVec2* pOut,ImFont* self,float size,float max_width,float wrap_width,const char* text_begin);
extern bool DragScalarN(const char* label,ImGuiDataType data_type,void* p_data,int components);
extern void Indent();
extern bool DragFloat3(const char* label,float v[3]);
extern bool IsItemHovered();
extern void TextUnformatted(const char* text);
extern ImGuiID DockSpaceOverViewport();

#ifdef __cplusplus
}
#endif
