#pragma once

#include "cimgui/cimgui.h"

#ifdef __cplusplus
extern "C" {
#endif

extern bool Storage_GetBool(ImGuiStorage* self,ImGuiID key,bool default_val);
extern int GetColumnsCount();
extern void TableSetupScrollFreeze(int cols,int rows);
extern void SetColorEditOptions(ImGuiColorEditFlags flags);
extern bool SliderAngle(const char* label,float* v_rad,float v_degrees_min,float v_degrees_max,const char* format,ImGuiSliderFlags flags);
extern void Font_BuildLookupTable(ImFont* self);
extern bool DragFloat(const char* label,float* v,float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void GetItemRectSize(ImVec2 *pOut);
extern void DrawList_PrimReserve(ImDrawList* self,int idx_count,int vtx_count);
extern bool IsMouseHoveringRect(const ImVec2 r_min,const ImVec2 r_max,bool clip);
extern void LogToFile(int auto_open_depth,const char* filename);
extern void Font_CalcTextSizeA(ImVec2 *pOut,ImFont* self,float size,float max_width,float wrap_width,const char* text_begin,const char* text_end,const char** remaining);
extern float GetTextLineHeight();
extern ImFont* FontAtlas_AddFontFromMemoryTTF(ImFontAtlas* self,void* font_data,int font_size,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern void FontAtlas_ClearInputData(ImFontAtlas* self);
extern void Color_HSV(ImColor *pOut,float h,float s,float v,float a);
extern void DrawList_PathBezierCubicCurveTo(ImDrawList* self,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,int num_segments);
extern float GetCursorPosX();
extern void SetNextItemOpen(bool is_open,ImGuiCond cond);
extern void DrawList_AddPolyline(ImDrawList* self,const ImVec2* points,int num_points,ImU32 col,ImDrawFlags flags,float thickness);
extern void GetWindowPos(ImVec2 *pOut);
extern void SetNextWindowFocus();
extern void FontAtlas_Clear(ImFontAtlas* self);
extern bool BeginCombo(const char* label,const char* preview_value,ImGuiComboFlags flags);
extern void GetItemRectMin(ImVec2 *pOut);
extern void GetMouseDragDelta(ImVec2 *pOut,ImGuiMouseButton button,float lock_threshold);
extern void FontAtlas_GetTexDataAsAlpha8(ImFontAtlas* self,unsigned char** out_pixels,int* out_width,int* out_height,int* out_bytes_per_pixel);
extern ImGuiTableSortSpecs* TableSortSpecs_TableSortSpecs();
extern void SetCursorPosX(float local_x);
extern void DrawList_PushClipRect(ImDrawList* self,const ImVec2 clip_rect_min,const ImVec2 clip_rect_max,bool intersect_with_current_clip_rect);
extern bool IsWindowCollapsed();
extern ImGuiMouseCursor GetMouseCursor();
extern void SetColumnOffset(int column_index,float offset_x);
extern ImFontGlyphRangesBuilder* FontGlyphRangesBuilder_FontGlyphRangesBuilder();
extern const char* GetStyleColorName(ImGuiCol idx);
extern void StyleColorsClassic(ImGuiStyle* dst);
extern void DrawList_ChannelsSetCurrent(ImDrawList* self,int n);
extern void GetItemRectMax(ImVec2 *pOut);
extern void DrawListSplitter_ClearFreeMemory(ImDrawListSplitter* self);
extern void ColorConvertHSVtoRGB(float h,float s,float v,float* out_r,float* out_g,float* out_b);
extern void LogButtons();
extern bool TableNextColumn();
extern void UpdatePlatformWindows();
extern void DrawList_AddQuadFilled(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col);
extern void DrawList_PathArcTo(ImDrawList* self,const ImVec2 center,float radius,float a_min,float a_max,int num_segments);
extern void ShowFontSelector(const char* label);
extern int FontAtlas_AddCustomRectRegular(ImFontAtlas* self,int width,int height);
extern const ImWchar* FontAtlas_GetGlyphRangesJapanese(ImFontAtlas* self);
extern int Storage_GetInt(ImGuiStorage* self,ImGuiID key,int default_val);
extern ImGuiViewport* Viewport_Viewport();
extern ImGuiWindowClass* WindowClass_WindowClass();
extern bool IsAnyMouseDown();
extern void PopButtonRepeat();
extern void FontAtlas_CalcCustomRectUV(ImFontAtlas* self,const ImFontAtlasCustomRect* rect,ImVec2* out_uv_min,ImVec2* out_uv_max);
extern const char* Font_CalcWordWrapPositionA(ImFont* self,float scale,const char* text,const char* text_end,float wrap_width);
extern void Separator();
extern void** Storage_GetVoidPtrRef(ImGuiStorage* self,ImGuiID key,void* default_val);
extern ImGuiViewport* FindViewportByID(ImGuiID id);
extern void EndListBox();
extern void NewLine();
extern const ImFontGlyph* Font_FindGlyphNoFallback(ImFont* self,ImWchar c);
extern bool ColorPicker4(const char* label,float col[4],ImGuiColorEditFlags flags,const float* ref_col);
extern bool InputFloat3(const char* label,float v[3],const char* format,ImGuiInputTextFlags flags);
extern bool IsItemToggledOpen();
extern void PopAllowKeyboardFocus();
extern bool SliderInt(const char* label,int* v,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern const ImWchar* FontAtlas_GetGlyphRangesThai(ImFontAtlas* self);
extern void IO_AddKeyEvent(ImGuiIO* self,ImGuiKey key,bool down);
extern void Style_ScaleAllSizes(ImGuiStyle* self,float scale_factor);
extern bool BeginListBox(const char* label,const ImVec2 size);
extern ImGuiID DockSpace(ImGuiID id,const ImVec2 size,ImGuiDockNodeFlags flags,const ImGuiWindowClass* window_class);
extern void EndDragDropTarget();
extern bool FontGlyphRangesBuilder_GetBit(ImFontGlyphRangesBuilder* self,size_t n);
extern void GetCursorScreenPos(ImVec2 *pOut);
extern bool DebugCheckVersionAndDataLayout(const char* version_str,size_t sz_io,size_t sz_style,size_t sz_vec2,size_t sz_vec4,size_t sz_drawvert,size_t sz_drawidx);
extern bool DragIntRange2(const char* label,int* v_current_min,int* v_current_max,float v_speed,int v_min,int v_max,const char* format,const char* format_max,ImGuiSliderFlags flags);
extern bool TextFilter_PassFilter(ImGuiTextFilter* self,const char* text,const char* text_end);
extern int GetMouseClickedCount(ImGuiMouseButton button);
extern bool IsAnyItemActive();
extern int GetKeyIndex(ImGuiKey key);
extern void GetWindowContentRegionMax(ImVec2 *pOut);
extern ImFont* FontAtlas_AddFont(ImFontAtlas* self,const ImFontConfig* font_cfg);
extern void FontGlyphRangesBuilder_AddRanges(ImFontGlyphRangesBuilder* self,const ImWchar* ranges);
extern void Storage_SetBool(ImGuiStorage* self,ImGuiID key,bool val);
extern void EndDisabled();
extern void End();
extern bool InputFloat4(const char* label,float v[4],const char* format,ImGuiInputTextFlags flags);
extern bool DragFloat3(const char* label,float v[3],float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern float GetScrollX();
extern void SetNextWindowPos(const ImVec2 pos,ImGuiCond cond,const ImVec2 pivot);
extern void ShowUserGuide();
extern bool IsWindowHovered(ImGuiHoveredFlags flags);
extern int TableGetRowIndex();
extern double GetTime();
extern bool BeginPopupModal(const char* name,bool* p_open,ImGuiWindowFlags flags);
extern ImDrawData* GetDrawData();
extern void DrawList_PrimWriteVtx(ImDrawList* self,const ImVec2 pos,const ImVec2 uv,ImU32 col);
extern int* Storage_GetIntRef(ImGuiStorage* self,ImGuiID key,int default_val);
extern void BeginTooltip();
extern void FontGlyphRangesBuilder_SetBit(ImFontGlyphRangesBuilder* self,size_t n);
extern void PopClipRect();
extern bool DragFloat2(const char* label,float v[2],float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern bool SliderScalarN(const char* label,ImGuiDataType data_type,void* p_data,int components,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern void DrawList_GetClipRectMin(ImVec2 *pOut,ImDrawList* self);
extern void DrawList_PrimVtx(ImDrawList* self,const ImVec2 pos,const ImVec2 uv,ImU32 col);
extern bool SliderFloat4(const char* label,float v[4],float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void TextUnformatted(const char* text,const char* text_end);
extern ImDrawList* DrawList_DrawList(const ImDrawListSharedData* shared_data);
extern ImGuiTextFilter* TextFilter_TextFilter(const char* default_filter);
extern ImDrawList* GetWindowDrawList();
extern bool IsItemEdited();
extern void SetNextFrameWantCaptureMouse(bool want_capture_mouse);
extern ImGuiTableColumnSortSpecs* TableColumnSortSpecs_TableColumnSortSpecs();
extern void PushButtonRepeat(bool repeat);
extern void DrawList_AddTriangle(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col,float thickness);
extern ImGuiStyle* Style_Style();
extern void Font_RenderChar(ImFont* self,ImDrawList* draw_list,float size,const ImVec2 pos,ImU32 col,ImWchar c);
extern ImFont* Font_Font();
extern void DrawData_Clear(ImDrawData* self);
extern void* Storage_GetVoidPtr(ImGuiStorage* self,ImGuiID key);
extern ImDrawData* DrawData_DrawData();
extern void DrawList_PathLineTo(ImDrawList* self,const ImVec2 pos);
extern void ProgressBar(float fraction,const ImVec2 size_arg,const char* overlay);
extern ImFont* FontAtlas_AddFontFromFileTTF(ImFontAtlas* self,const char* filename,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern const ImGuiPayload* AcceptDragDropPayload(const char* type,ImGuiDragDropFlags flags);
extern bool BeginMainMenuBar();
extern void PushFont(ImFont* font);
extern void ShowDemoWindow(bool* p_open);
extern ImDrawListSharedData* GetDrawListSharedData();
extern float GetWindowWidth();
extern void OpenPopupOnItemClick(const char* str_id,ImGuiPopupFlags popup_flags);
extern void DrawList_GetClipRectMax(ImVec2 *pOut,ImDrawList* self);
extern void IO_AddKeyAnalogEvent(ImGuiIO* self,ImGuiKey key,bool down,float v);
extern float Storage_GetFloat(ImGuiStorage* self,ImGuiID key,float default_val);
extern void TextFilter_Clear(ImGuiTextFilter* self);
extern bool InputInt4(const char* label,int v[4],ImGuiInputTextFlags flags);
extern void ListClipper_End(ImGuiListClipper* self);
extern float GetScrollMaxY();
extern void PushTextWrapPos(float wrap_local_pos_x);
extern bool ColorEdit4(const char* label,float col[4],ImGuiColorEditFlags flags);
extern const char* TextBuffer_c_str(ImGuiTextBuffer* self);
extern void SaveIniSettingsToDisk(const char* ini_filename);
extern const ImWchar* FontAtlas_GetGlyphRangesDefault(ImFontAtlas* self);
extern void RenderPlatformWindowsDefault(void* platform_render_arg,void* renderer_render_arg);
extern const char* SaveIniSettingsToMemory(size_t* out_ini_size);
extern void SetNextItemWidth(float item_width);
extern ImGuiTableColumnFlags TableGetColumnFlags(int column_n);
extern bool Payload_IsDataType(ImGuiPayload* self,const char* type);
extern void SetItemAllowOverlap();
extern void SetNextWindowViewport(ImGuiID viewport_id);
extern void EndFrame();
extern void GetContentRegionMax(ImVec2 *pOut);
extern bool Payload_IsPreview(ImGuiPayload* self);
extern void TableHeadersRow();
extern void FontGlyphRangesBuilder_AddText(ImFontGlyphRangesBuilder* self,const char* text,const char* text_end);
extern void ShowAboutWindow(bool* p_open);
extern const ImWchar* FontAtlas_GetGlyphRangesChineseSimplifiedCommon(ImFontAtlas* self);
extern void EndChildFrame();
extern float GetFrameHeight();
extern bool SliderInt2(const char* label,int v[2],int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void FontGlyphRangesBuilder_Clear(ImFontGlyphRangesBuilder* self);
extern void SameLine(float offset_from_start_x,float spacing);
extern ImTextureID DrawCmd_GetTexID(ImDrawCmd* self);
extern void SetNextWindowClass(const ImGuiWindowClass* window_class);
extern void IO_SetAppAcceptingEvents(ImGuiIO* self,bool accepting_events);
extern bool ShowStyleSelector(const char* label);
extern ImGuiTextBuffer* TextBuffer_TextBuffer();
extern void FontAtlas_ClearTexData(ImFontAtlas* self);
extern int GetColumnIndex();
extern void SetCursorPosY(float local_y);
extern ImGuiPlatformMonitor* PlatformMonitor_PlatformMonitor();
extern void DrawList_AddConvexPolyFilled(ImDrawList* self,const ImVec2* points,int num_points,ImU32 col);
extern void DrawList_AddDrawCmd(ImDrawList* self);
extern bool BeginChildFrame(ImGuiID id,const ImVec2 size,ImGuiWindowFlags flags);
extern void DrawData_ScaleClipRects(ImDrawData* self,const ImVec2 fb_scale);
extern void Viewport_GetCenter(ImVec2 *pOut,ImGuiViewport* self);
extern bool SliderFloat3(const char* label,float v[3],float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern float GetCursorPosY();
extern void DrawList_AddNgonFilled(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments);
extern void CalcTextSize(ImVec2 *pOut,const char* text,const char* text_end,bool hide_text_after_double_hash,float wrap_width);
extern void SetStateStorage(ImGuiStorage* storage);
extern void DestroyContext(ImGuiContext* ctx);
extern bool BeginPopup(const char* str_id,ImGuiWindowFlags flags);
extern bool InputFloat(const char* label,float* v,float step,float step_fast,const char* format,ImGuiInputTextFlags flags);
extern void EndTabItem();
extern void EndMenu();
extern const ImVec4* GetStyleColorVec4(ImGuiCol idx);
extern void TableSetupColumn(const char* label,ImGuiTableColumnFlags flags,float init_width_or_weight,ImGuiID user_id);
extern bool BeginPopupContextItem(const char* str_id,ImGuiPopupFlags popup_flags);
extern bool InputInt2(const char* label,int v[2],ImGuiInputTextFlags flags);
extern bool IsMouseReleased(ImGuiMouseButton button);
extern void SetKeyboardFocusHere(int offset);
extern void DrawListSplitter_Split(ImDrawListSplitter* self,ImDrawList* draw_list,int count);
extern ImFontAtlas* FontAtlas_FontAtlas();
extern void InputTextCallbackData_ClearSelection(ImGuiInputTextCallbackData* self);
extern ImGuiContext* CreateContext(ImFontAtlas* shared_font_atlas);
extern void TableNextRow(ImGuiTableRowFlags row_flags,float min_row_height);
extern void TableSetBgColor(ImGuiTableBgTarget target,ImU32 color,int column_n);
extern void IO_AddMouseButtonEvent(ImGuiIO* self,int button,bool down);
extern bool BeginMenu(const char* label,bool enabled);
extern void SetNextWindowContentSize(const ImVec2 size);
extern ImFontConfig* FontConf_FontConfig();
extern bool TextFilter_IsActive(ImGuiTextFilter* self);
extern void EndPopup();
extern bool Begin(const char* name,bool* p_open,ImGuiWindowFlags flags);
extern void EndMainMenuBar();
extern void ShowStyleEditor(ImGuiStyle* ref);
extern void DrawList_ChannelsMerge(ImDrawList* self);
extern void BeginGroup();
extern bool Payload_IsDelivery(ImGuiPayload* self);
extern ImGuiPlatformIO* PlatformIO_PlatformIO();
extern void ColorConvertRGBtoHSV(float r,float g,float b,float* out_h,float* out_s,float* out_v);
extern void BeginDisabled(bool disabled);
extern ImGuiIO* GetIO();
extern ImDrawCmd* DrawCmd_DrawCmd();
extern void DrawList_PopClipRect(ImDrawList* self);
extern void FontAtlas_SetTexID(ImFontAtlas* self,ImTextureID id);
extern bool IsKeyPressed(ImGuiKey key,bool repeat);
extern void TextFilter_Build(ImGuiTextFilter* self);
extern void GetCursorStartPos(ImVec2 *pOut);
extern const char* GetVersion();
extern void DebugTextEncoding(const char* text);
extern bool DragInt4(const char* label,int v[4],float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern const ImGuiPayload* GetDragDropPayload();
extern float Font_GetCharAdvance(ImFont* self,ImWchar c);
extern void InputTextCallbackData_SelectAll(ImGuiInputTextCallbackData* self);
extern void LogToClipboard(int auto_open_depth);
extern void ListClipper_Begin(ImGuiListClipper* self,int items_count,float items_height);
extern void Payload_Clear(ImGuiPayload* self);
extern bool DragInt2(const char* label,int v[2],float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern bool ColorButton(const char* desc_id,const ImVec4 col,ImGuiColorEditFlags flags,const ImVec2 size);
extern void FontAtlas_ClearFonts(ImFontAtlas* self);
extern void FontGlyphRangesBuilder_AddChar(ImFontGlyphRangesBuilder* self,ImWchar c);
extern bool IsWindowFocused(ImGuiFocusedFlags flags);
extern void TableHeader(const char* label);
extern bool DragFloatRange2(const char* label,float* v_current_min,float* v_current_max,float v_speed,float v_min,float v_max,const char* format,const char* format_max,ImGuiSliderFlags flags);
extern void DrawList_ChannelsSplit(ImDrawList* self,int count);
extern bool Checkbox(const char* label,bool* v);
extern bool DragFloat4(const char* label,float v[4],float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern float GetColumnOffset(int column_index);
extern void Font_AddRemapChar(ImFont* self,ImWchar dst,ImWchar src,bool overwrite_dst);
extern void Font_AddGlyph(ImFont* self,const ImFontConfig* src_cfg,ImWchar c,float x0,float y0,float x1,float y1,float u0,float v0,float u1,float v1,float advance_x);
extern ImGuiPayload* Payload_Payload();
extern void IO_AddMouseWheelEvent(ImGuiIO* self,float wh_x,float wh_y);
extern void Bullet();
extern ImU32 ColorConvertFloat4ToU32(const ImVec4 in);
extern bool IsItemClicked(ImGuiMouseButton mouse_button);
extern void PopItemWidth();
extern void DrawList_PathRect(ImDrawList* self,const ImVec2 rect_min,const ImVec2 rect_max,float rounding,ImDrawFlags flags);
extern const ImWchar* FontAtlas_GetGlyphRangesVietnamese(ImFontAtlas* self);
extern void GetMousePos(ImVec2 *pOut);
extern bool InputScalar(const char* label,ImGuiDataType data_type,void* p_data,const void* p_step,const void* p_step_fast,const char* format,ImGuiInputTextFlags flags);
extern bool InputText(const char* label,char* buf,size_t buf_size,ImGuiInputTextFlags flags,ImGuiInputTextCallback callback,void* user_data);
extern void MemFree(void* ptr);
extern bool Font_IsGlyphRangeUnused(ImFont* self,unsigned int c_begin,unsigned int c_last);
extern bool ArrowButton(const char* str_id,ImGuiDir dir);
extern bool SliderScalar(const char* label,ImGuiDataType data_type,void* p_data,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern bool FontAtlas_IsBuilt(ImFontAtlas* self);
extern void SetItemDefaultFocus();
extern void DrawList_AddRect(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col,float rounding,ImDrawFlags flags,float thickness);
extern ImDrawList* DrawList_CloneOutput(ImDrawList* self);
extern void SetScrollHereY(float center_y_ratio);
extern void DrawList_AddQuad(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col,float thickness);
extern void IO_AddInputCharacter(ImGuiIO* self,unsigned int c);
extern ImGuiIO* IO_IO();
extern void DrawList_PathLineToMergeDuplicate(ImDrawList* self,const ImVec2 pos);
extern void SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard);
extern bool IsItemDeactivatedAfterEdit();
extern bool ColorEdit3(const char* label,float col[3],ImGuiColorEditFlags flags);
extern bool DragInt(const char* label,int* v,float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern float GetFontSize();
extern ImGuiPlatformImeData* PlatformeData_PlatformeData();
extern void Viewport_GetWorkCenter(ImVec2 *pOut,ImGuiViewport* self);
extern float GetWindowHeight();
extern void GetMousePosOnOpeningCurrentPopup(ImVec2 *pOut);
extern void ResetMouseDragDelta(ImGuiMouseButton button);
extern void DrawList_PushClipRectFullScreen(ImDrawList* self);
extern bool BeginMenuBar();
extern const ImWchar* FontAtlas_GetGlyphRangesChineseFull(ImFontAtlas* self);
extern bool SliderInt4(const char* label,int v[4],int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void DrawListSplitter_Merge(ImDrawListSplitter* self,ImDrawList* draw_list);
extern void DrawList_PrimRectUV(ImDrawList* self,const ImVec2 a,const ImVec2 b,const ImVec2 uv_a,const ImVec2 uv_b,ImU32 col);
extern bool InputDouble(const char* label,double* v,double step,double step_fast,const char* format,ImGuiInputTextFlags flags);
extern bool IsItemDeactivated();
extern int GetFrameCount();
extern bool IsAnyItemHovered();
extern void DrawList_AddCallback(ImDrawList* self,ImDrawCallback callback,void* callback_data);
extern bool InputScalarN(const char* label,ImGuiDataType data_type,void* p_data,int components,const void* p_step,const void* p_step_fast,const char* format,ImGuiInputTextFlags flags);
extern bool BeginTabItem(const char* label,bool* p_open,ImGuiTabItemFlags flags);
extern void SetMouseCursor(ImGuiMouseCursor cursor_type);
extern bool FontAtlasCustomRect_IsPacked(ImFontAtlasCustomRect* self);
extern bool SetDragDropPayload(const char* type,const void* data,size_t sz,ImGuiCond cond);
extern bool SliderFloat(const char* label,float* v,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern bool VSliderInt(const char* label,const ImVec2 size,int* v,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void DrawList_AddageRounded(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p_min,const ImVec2 p_max,const ImVec2 uv_min,const ImVec2 uv_max,ImU32 col,float rounding,ImDrawFlags flags);
extern bool Button(const char* label,const ImVec2 size);
extern bool IsItemVisible();
extern void DrawList_AddBezierQuadratic(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col,float thickness,int num_segments);
extern bool TextFilter_Draw(ImGuiTextFilter* self,const char* label,float width);
extern void IO_SetKeyEventNativeData(ImGuiIO* self,ImGuiKey key,int native_keycode,int native_scancode,int native_legacy_index);
extern bool IsMouseDragging(ImGuiMouseButton button,float lock_threshold);
extern void Render();
extern int FontAtlas_AddCustomRectFontGlyph(ImFontAtlas* self,ImFont* font,ImWchar id,int width,int height,float advance_x,const ImVec2 offset);
extern void* MemAlloc(size_t size);
extern void SetNextWindowSizeConstraints(const ImVec2 size_min,const ImVec2 size_max,ImGuiSizeCallback custom_callback,void* custom_callback_data);
extern void FontGlyphRangesBuilder_BuildRanges(ImFontGlyphRangesBuilder* self,ImVector_ImWchar* out_ranges);
extern void SetNextWindowDockID(ImGuiID dock_id,ImGuiCond cond);
extern bool DragInt3(const char* label,int v[3],float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern const char* GetKeyName(ImGuiKey key);
extern void SetTabItemClosed(const char* tab_or_docked_window_label);
extern void DrawList_PathArcToFast(ImDrawList* self,const ImVec2 center,float radius,int a_min_of_12,int a_max_of_12);
extern bool DragScalarN(const char* label,ImGuiDataType data_type,void* p_data,int components,float v_speed,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern void SetColumnWidth(int column_index,float width);
extern void DrawList_PrimUnreserve(ImDrawList* self,int idx_count,int vtx_count);
extern void DestroyPlatformWindows();
extern void LoadIniSettingsFromMemory(const char* ini_data,size_t ini_size);
extern bool FontAtlas_Build(ImFontAtlas* self);
extern void InputTextCallbackData_InsertChars(ImGuiInputTextCallbackData* self,int pos,const char* text,const char* text_end);
extern bool FontAtlas_GetMouseCursorTexData(ImFontAtlas* self,ImGuiMouseCursor cursor,ImVec2* out_offset,ImVec2* out_size,ImVec2 out_uv_border[2],ImVec2 out_uv_fill[2]);
extern void DrawList_AddNgon(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments,float thickness);
extern void ListClipper_ForceDisplayRangeByIndices(ImGuiListClipper* self,int item_min,int item_max);
extern bool IsMousePosValid(const ImVec2* mouse_pos);
extern void DrawListSplitter_SetCurrentChannel(ImDrawListSplitter* self,ImDrawList* draw_list,int channel_idx);
extern ImGuiViewport* FindViewportByPlatformHandle(void* platform_handle);
extern int GetKeyPressedAmount(ImGuiKey key,float repeat_delay,float rate);
extern void SetNextWindowCollapsed(bool collapsed,ImGuiCond cond);
extern void PushItemWidth(float item_width);
extern void DrawList_AddRectFilled(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col,float rounding,ImDrawFlags flags);
extern bool SmallButton(const char* label);
extern void EndTabBar();
extern void DrawListSplitter_Clear(ImDrawListSplitter* self);
extern bool BeginDragDropTarget();
extern void ShowDebugLogWindow(bool* p_open);
extern void EndGroup();
extern void DrawList_PathClear(ImDrawList* self);
extern ImGuiID GetWindowDockID();
extern void ShowMetricsWindow(bool* p_open);
extern bool BeginTable(const char* str_id,int column,ImGuiTableFlags flags,const ImVec2 outer_size,float inner_width);
extern int TableGetColumnCount();
extern void DrawList_PrimWriteIdx(ImDrawList* self,ImDrawIdx idx);
extern bool InputTextMultiline(const char* label,char* buf,size_t buf_size,const ImVec2 size,ImGuiInputTextFlags flags,ImGuiInputTextCallback callback,void* user_data);
extern void TableSetColumnEnabled(int column_n,bool v);
extern void DrawData_DeIndexAllBuffers(ImDrawData* self);
extern void Font_RenderText(ImFont* self,ImDrawList* draw_list,float size,const ImVec2 pos,ImU32 col,const ImVec4 clip_rect,const char* text_begin,const char* text_end,float wrap_width,bool cpu_fine_clip);
extern bool IsKeyDown(ImGuiKey key);
extern const char* GetClipboardText();
extern bool IsAnyItemFocused();
extern bool InputInt(const char* label,int* v,int step,int step_fast,ImGuiInputTextFlags flags);
extern bool InputInt3(const char* label,int v[3],ImGuiInputTextFlags flags);
extern bool IsWindowAppearing();
extern void Storage_BuildSortByKey(ImGuiStorage* self);
extern void SetClipboardText(const char* text);
extern void FontAtlas_GetTexDataAsRGBA32(ImFontAtlas* self,unsigned char** out_pixels,int* out_width,int* out_height,int* out_bytes_per_pixel);
extern bool InputTextCallbackData_HasSelection(ImGuiInputTextCallbackData* self);
extern bool ListClipper_Step(ImGuiListClipper* self);
extern bool BeginPopupContextVoid(const char* str_id,ImGuiPopupFlags popup_flags);
extern bool IsWindowDocked();
extern const ImFontGlyph* Font_FindGlyph(ImFont* self,ImWchar c);
extern void EndChild();
extern void SetCursorScreenPos(const ImVec2 pos);
extern void DrawList_PushTextureID(ImDrawList* self,ImTextureID texture_id);
extern void EndMenuBar();
extern void SetNextWindowBgAlpha(float alpha);
extern ImGuiOnceUponAFrame* OnceUponAFrame_OnceUponAFrame();
extern ImFont* FontAtlas_AddFontFromMemoryCompressedBase85TTF(ImFontAtlas* self,const char* compressed_font_data_base85,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern float GetTextLineHeightWithSpacing();
extern ImFontAtlasCustomRect* FontAtlasCustomRect_FontAtlasCustomRect();
extern bool IsMouseDoubleClicked(ImGuiMouseButton button);
extern void LogToTTY(int auto_open_depth);
extern bool VSliderFloat(const char* label,const ImVec2 size,float* v,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void DrawList_AddLine(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,ImU32 col,float thickness);
extern void LoadIniSettingsFromDisk(const char* ini_filename);
extern int TableGetColumnIndex();
extern void DrawList_PrimRect(ImDrawList* self,const ImVec2 a,const ImVec2 b,ImU32 col);
extern void Font_ClearOutputData(ImFont* self);
extern ImGuiID DockSpaceOverViewport(const ImGuiViewport* viewport,ImGuiDockNodeFlags flags,const ImGuiWindowClass* window_class);
extern ImGuiContext* GetCurrentContext();
extern float GetFrameHeightWithSpacing();
extern bool VSliderScalar(const char* label,const ImVec2 size,ImGuiDataType data_type,void* p_data,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern float GetScrollMaxX();
extern void PopStyleColor(int count);
extern void CloseCurrentPopup();
extern void SetNextWindowSize(const ImVec2 size,ImGuiCond cond);
extern ImGuiViewport* GetMainViewport();
extern void Storage_SetAllInt(ImGuiStorage* self,int val);
extern void GetWindowSize(ImVec2 *pOut);
extern void StyleColorsDark(ImGuiStyle* dst);
extern void Color_SetHSV(ImColor* self,float h,float s,float v,float a);
extern ImDrawListSplitter* DrawListSplitter_DrawListSplitter();
extern float GetWindowDpiScale();
extern void Unindent(float indent_w);
extern void IO_AddInputCharactersUTF8(ImGuiIO* self,const char* str);
extern void ColorConvertU32ToFloat4(ImVec4 *pOut,ImU32 in);
extern void EndDragDropSource();
extern ImGuiInputTextCallbackData* InputTextCallbackData_InputTextCallbackData();
extern ImGuiPlatformIO* GetPlatformIO();
extern void Indent(float indent_w);
extern void NewFrame();
extern void SetWindowFontScale(float scale);
extern void DrawList_Addage(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p_min,const ImVec2 p_max,const ImVec2 uv_min,const ImVec2 uv_max,ImU32 col);
extern float CalcItemWidth();
extern void PopID();
extern void IO_AddMousePosEvent(ImGuiIO* self,float x,float y);
extern const ImWchar* FontAtlas_GetGlyphRangesCyrillic(ImFontAtlas* self);
extern void Font_SetGlyphVisible(ImFont* self,ImWchar c,bool visible);
extern float GetScrollY();
extern void Storage_SetFloat(ImGuiStorage* self,ImGuiID key,float val);
extern void DrawList_AddTriangleFilled(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col);
extern void Columns(int count,const char* id,bool border);
extern void GetFontTexUvWhitePixel(ImVec2 *pOut);
extern bool InputTextWithHint(const char* label,const char* hint,char* buf,size_t buf_size,ImGuiInputTextFlags flags,ImGuiInputTextCallback callback,void* user_data);
extern bool DragScalar(const char* label,ImGuiDataType data_type,void* p_data,float v_speed,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern void EndTooltip();
extern void DrawList_AddBezierCubic(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col,float thickness,int num_segments);
extern void EndCombo();
extern void PushClipRect(const ImVec2 clip_rect_min,const ImVec2 clip_rect_max,bool intersect_with_current_clip_rect);
extern void TreePop();
extern void DrawList_AddRectFilledMultiColor(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col_upr_left,ImU32 col_upr_right,ImU32 col_bot_right,ImU32 col_bot_left);
extern void IO_AddMouseViewportEvent(ImGuiIO* self,ImGuiID id);
extern void ShowStackToolWindow(bool* p_open);
extern bool ColorPicker3(const char* label,float col[3],ImGuiColorEditFlags flags);
extern ImGuiStyle* GetStyle();
extern float GetTreeNodeToLabelSpacing();
extern ImGuiViewport* GetWindowViewport();
extern bool SliderInt3(const char* label,int v[3],int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void IO_AddFocusEvent(ImGuiIO* self,bool focused);
extern void StyleColorsLight(ImGuiStyle* dst);
extern void PopTextWrapPos();
extern void IO_AddInputCharacterUTF16(ImGuiIO* self,ImWchar16 c);
extern bool IsItemActive();
extern ImGuiListClipper* ListClipper_ListClipper();
extern void Storage_SetVoidPtr(ImGuiStorage* self,ImGuiID key,void* val);
extern void DrawList_AddageQuad(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,const ImVec2 uv1,const ImVec2 uv2,const ImVec2 uv3,const ImVec2 uv4,ImU32 col);
extern const ImWchar* FontAtlas_GetGlyphRangesKorean(ImFontAtlas* self);
extern void GetWindowContentRegionMin(ImVec2 *pOut);
extern void DrawList_PathStroke(ImDrawList* self,ImU32 col,ImDrawFlags flags,float thickness);
extern float GetColumnWidth(int column_index);
extern bool SliderFloat2(const char* label,float v[2],float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void DrawList_AddCircleFilled(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments);
extern void DrawList_PrimQuadUV(ImDrawList* self,const ImVec2 a,const ImVec2 b,const ImVec2 c,const ImVec2 d,const ImVec2 uv_a,const ImVec2 uv_b,const ImVec2 uv_c,const ImVec2 uv_d,ImU32 col);
extern bool BeginTabBar(const char* str_id,ImGuiTabBarFlags flags);
extern bool IsItemActivated();
extern bool TabItemButton(const char* label,ImGuiTabItemFlags flags);
extern bool TableSetColumnIndex(int column_n);
extern bool IsKeyReleased(ImGuiKey key);
extern bool IsMouseDown(ImGuiMouseButton button);
extern const char* Font_GetDebugName(ImFont* self);
extern void GetCursorPos(ImVec2 *pOut);
extern void NextColumn();
extern void DrawList_PopTextureID(ImDrawList* self);
extern ImFont* GetFont();
extern bool BeginPopupContextWindow(const char* str_id,ImGuiPopupFlags popup_flags);
extern void Dummy(const ImVec2 size);
extern void EndTable();
extern bool InvisibleButton(const char* str_id,const ImVec2 size,ImGuiButtonFlags flags);
extern bool IsMouseClicked(ImGuiMouseButton button,bool repeat);
extern void SetCurrentContext(ImGuiContext* ctx);
extern void IO_ClearInputCharacters(ImGuiIO* self);
extern void PopStyleVar(int count);
extern void SetCursorPos(const ImVec2 local_pos);
extern void AlignTextToFramePadding();
extern float* Storage_GetFloatRef(ImGuiStorage* self,ImGuiID key,float default_val);
extern bool IsItemFocused();
extern void PopFont();
extern void GetContentRegionAvail(ImVec2 *pOut);
extern ImGuiStorage* GetStateStorage();
extern bool IsItemHovered(ImGuiHoveredFlags flags);
extern void DrawList_AddCircle(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments,float thickness);
extern void DrawList_PathBezierQuadraticCurveTo(ImDrawList* self,const ImVec2 p2,const ImVec2 p3,int num_segments);
extern ImFont* FontAtlas_AddFontFromMemoryCompressedTTF(ImFontAtlas* self,const void* compressed_font_data,int compressed_font_size,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern void SetScrollHereX(float center_x_ratio);
extern void IO_ClearInputKeys(ImGuiIO* self);
extern bool* Storage_GetBoolRef(ImGuiStorage* self,ImGuiID key,bool default_val);
extern void Spacing();
extern void Font_GrowIndex(ImFont* self,int new_size);
extern void Storage_Clear(ImGuiStorage* self);
extern bool BeginDragDropSource(ImGuiDragDropFlags flags);
extern ImFontAtlasCustomRect* FontAtlas_GetCustomRectByIndex(ImFontAtlas* self,int index);
extern void Storage_SetInt(ImGuiStorage* self,ImGuiID key,int val);
extern bool Font_IsLoaded(ImFont* self);
extern ImGuiTableSortSpecs* TableGetSortSpecs();
extern ImFont* FontAtlas_AddFontDefault(ImFontAtlas* self,const ImFontConfig* font_cfg);
extern void PushAllowKeyboardFocus(bool allow_keyboard_focus);
extern void DrawList_PathFillConvex(ImDrawList* self,ImU32 col);
extern void InputTextCallbackData_DeleteChars(ImGuiInputTextCallbackData* self,int pos,int bytes_count);
extern bool InputFloat2(const char* label,float v[2],const char* format,ImGuiInputTextFlags flags);
extern void LogFinish();

#ifdef __cplusplus
}
#endif
