#pragma once

#include "cimgui/cimgui.h"

#ifdef __cplusplus
extern "C" {
#endif

extern bool IsAnyMouseDown();
extern ImGuiPlatformIO* ImGuiPlatformIO_ImGuiPlatformIO();
extern bool BeginListBox(const char* label,const ImVec2 size);
extern void PopStyleColor(int count);
extern bool VSliderFloat(const char* label,const ImVec2 size,float* v,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void ImDrawList_AddImage(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p_min,const ImVec2 p_max,const ImVec2 uv_min,const ImVec2 uv_max,ImU32 col);
extern void ImFontAtlas_GetTexDataAsRGBA32(ImFontAtlas* self,unsigned char** out_pixels,int* out_width,int* out_height,int* out_bytes_per_pixel);
extern ImGuiViewport* GetMainViewport();
extern float GetWindowWidth();
extern void ImDrawList_PrimUnreserve(ImDrawList* self,int idx_count,int vtx_count);
extern void EndDragDropSource();
extern bool ImFontGlyphRangesBuilder_GetBit(ImFontGlyphRangesBuilder* self,size_t n);
extern bool DragFloat2(const char* label,float v[2],float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void EndFrame();
extern void NewLine();
extern ImDrawData* ImDrawData_ImDrawData();
extern void ImDrawList_AddConvexPolyFilled(ImDrawList* self,const ImVec2* points,int num_points,ImU32 col);
extern void ImDrawList_PrimVtx(ImDrawList* self,const ImVec2 pos,const ImVec2 uv,ImU32 col);
extern bool SetDragDropPayload(const char* type,const void* data,size_t sz,ImGuiCond cond);
extern void ShowFontSelector(const char* label);
extern void ImDrawData_DeIndexAllBuffers(ImDrawData* self);
extern void Indent(float indent_w);
extern bool IsItemFocused();
extern void ImDrawList_PathLineTo(ImDrawList* self,const ImVec2 pos);
extern ImGuiStyle* ImGuiStyle_ImGuiStyle();
extern bool BeginTable(const char* str_id,int column,ImGuiTableFlags flags,const ImVec2 outer_size,float inner_width);
extern void ImDrawList_AddBezierQuadratic(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col,float thickness,int num_segments);
extern ImGuiViewport* ImGuiViewport_ImGuiViewport();
extern void DestroyContext(ImGuiContext* ctx);
extern void PushAllowKeyboardFocus(bool allow_keyboard_focus);
extern bool SliderInt(const char* label,int* v,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void ImDrawData_ScaleClipRects(ImDrawData* self,const ImVec2 fb_scale);
extern void ImFontAtlas_Clear(ImFontAtlas* self);
extern const ImWchar* ImFontAtlas_GetGlyphRangesDefault(ImFontAtlas* self);
extern void SetNextItemOpen(bool is_open,ImGuiCond cond);
extern void ImDrawList_AddTriangle(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col,float thickness);
extern void ImGuiViewport_GetCenter(ImVec2 *pOut,ImGuiViewport* self);
extern void ImFontGlyphRangesBuilder_AddChar(ImFontGlyphRangesBuilder* self,ImWchar c);
extern bool IsItemActive();
extern void StyleColorsLight(ImGuiStyle* dst);
extern const ImWchar* ImFontAtlas_GetGlyphRangesChineseSimplifiedCommon(ImFontAtlas* self);
extern void SetNextWindowFocus();
extern bool DragInt4(const char* label,int v[4],float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void EndTabBar();
extern ImGuiID GetWindowDockID();
extern int TableGetColumnIndex();
extern const char* GetVersion();
extern void ImDrawList_AddRectFilledMultiColor(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col_upr_left,ImU32 col_upr_right,ImU32 col_bot_right,ImU32 col_bot_left);
extern ImGuiTableColumnSortSpecs* ImGuiTableColumnSortSpecs_ImGuiTableColumnSortSpecs();
extern void SetCursorPosX(float local_x);
extern void ImGuiInputTextCallbackData_SelectAll(ImGuiInputTextCallbackData* self);
extern int ImGuiStorage_GetInt(ImGuiStorage* self,ImGuiID key,int default_val);
extern void ImDrawList_GetClipRectMin(ImVec2 *pOut,ImDrawList* self);
extern void SameLine(float offset_from_start_x,float spacing);
extern void SetClipboardText(const char* text);
extern float GetScrollMaxX();
extern bool SliderFloat2(const char* label,float v[2],float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void ImDrawList_AddRectFilled(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col,float rounding,ImDrawFlags flags);
extern const ImVec4* GetStyleColorVec4(ImGuiCol idx);
extern bool InputFloat2(const char* label,float v[2],const char* format,ImGuiInputTextFlags flags);
extern bool SliderFloat4(const char* label,float v[4],float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern bool IsWindowFocused(ImGuiFocusedFlags flags);
extern void ImDrawList_PathBezierQuadraticCurveTo(ImDrawList* self,const ImVec2 p2,const ImVec2 p3,int num_segments);
extern bool IsWindowCollapsed();
extern bool TableNextColumn();
extern const ImWchar* ImFontAtlas_GetGlyphRangesJapanese(ImFontAtlas* self);
extern void ColorConvertRGBtoHSV(float r,float g,float b,float* out_h,float* out_s,float* out_v);
extern void ImDrawList_PushClipRectFullScreen(ImDrawList* self);
extern int ImFontAtlas_AddCustomRectRegular(ImFontAtlas* self,int width,int height);
extern void* MemAlloc(size_t size);
extern bool BeginMainMenuBar();
extern ImDrawList* GetWindowDrawList();
extern bool BeginMenuBar();
extern bool SmallButton(const char* label);
extern void ImGuiInputTextCallbackData_DeleteChars(ImGuiInputTextCallbackData* self,int pos,int bytes_count);
extern bool InvisibleButton(const char* str_id,const ImVec2 size,ImGuiButtonFlags flags);
extern bool IsMousePosValid(const ImVec2* mouse_pos);
extern ImFont* ImFont_ImFont();
extern bool SliderInt4(const char* label,int v[4],int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern ImDrawCmd* ImDrawCmd_ImDrawCmd();
extern void SetNextWindowDockID(ImGuiID dock_id,ImGuiCond cond);
extern void ImGuiStorage_SetFloat(ImGuiStorage* self,ImGuiID key,float val);
extern bool BeginPopupContextVoid(const char* str_id,ImGuiPopupFlags popup_flags);
extern ImGuiID DockSpace(ImGuiID id,const ImVec2 size,ImGuiDockNodeFlags flags,const ImGuiWindowClass* window_class);
extern bool ImFontAtlas_Build(ImFontAtlas* self);
extern bool ImFont_IsLoaded(ImFont* self);
extern const char* ImFont_GetDebugName(ImFont* self);
extern bool IsKeyPressed(ImGuiKey key,bool repeat);
extern void** ImGuiStorage_GetVoidPtrRef(ImGuiStorage* self,ImGuiID key,void* default_val);
extern void PopID();
extern void ImFontGlyphRangesBuilder_AddRanges(ImFontGlyphRangesBuilder* self,const ImWchar* ranges);
extern const ImFontGlyph* ImFont_FindGlyphNoFallback(ImFont* self,ImWchar c);
extern void ImGuiIO_AddMouseViewportEvent(ImGuiIO* self,ImGuiID id);
extern void TextUnformatted(const char* text,const char* text_end);
extern void UpdatePlatformWindows();
extern void ImDrawList_PathFillConvex(ImDrawList* self,ImU32 col);
extern bool Checkbox(const char* label,bool* v);
extern const ImWchar* ImFontAtlas_GetGlyphRangesVietnamese(ImFontAtlas* self);
extern void GetMousePos(ImVec2 *pOut);
extern void ImGuiTextFilter_Build(ImGuiTextFilter* self);
extern bool DebugCheckVersionAndDataLayout(const char* version_str,size_t sz_io,size_t sz_style,size_t sz_vec2,size_t sz_vec4,size_t sz_drawvert,size_t sz_drawidx);
extern bool DragFloatRange2(const char* label,float* v_current_min,float* v_current_max,float v_speed,float v_min,float v_max,const char* format,const char* format_max,ImGuiSliderFlags flags);
extern void ImDrawList_PathArcToFast(ImDrawList* self,const ImVec2 center,float radius,int a_min_of_12,int a_max_of_12);
extern const ImFontGlyph* ImFont_FindGlyph(ImFont* self,ImWchar c);
extern bool IsAnyItemActive();
extern void BeginDisabled(bool disabled);
extern void SetColumnWidth(int column_index,float width);
extern void SetCurrentContext(ImGuiContext* ctx);
extern void ImFont_RenderText(ImFont* self,ImDrawList* draw_list,float size,const ImVec2 pos,ImU32 col,const ImVec4 clip_rect,const char* text_begin,const char* text_end,float wrap_width,bool cpu_fine_clip);
extern ImGuiIO* ImGuiIO_ImGuiIO();
extern bool IsItemVisible();
extern bool BeginChildFrame(ImGuiID id,const ImVec2 size,ImGuiWindowFlags flags);
extern void ColorConvertU32ToFloat4(ImVec4 *pOut,ImU32 in);
extern int GetKeyPressedAmount(ImGuiKey key,float repeat_delay,float rate);
extern ImDrawListSplitter* ImDrawListSplitter_ImDrawListSplitter();
extern float GetFontSize();
extern void ImFont_BuildLookupTable(ImFont* self);
extern void ShowAboutWindow(bool* p_open);
extern void ImDrawListSplitter_Split(ImDrawListSplitter* self,ImDrawList* draw_list,int count);
extern void ImDrawList_AddDrawCmd(ImDrawList* self);
extern void ImDrawList_AddNgon(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments,float thickness);
extern bool Button(const char* label,const ImVec2 size);
extern void ImGuiStyle_ScaleAllSizes(ImGuiStyle* self,float scale_factor);
extern void LoadIniSettingsFromMemory(const char* ini_data,size_t ini_size);
extern ImGuiListClipper* ImGuiListClipper_ImGuiListClipper();
extern bool BeginPopupModal(const char* name,bool* p_open,ImGuiWindowFlags flags);
extern void GetWindowContentRegionMin(ImVec2 *pOut);
extern float GetCursorPosX();
extern const ImWchar* ImFontAtlas_GetGlyphRangesKorean(ImFontAtlas* self);
extern bool ColorPicker3(const char* label,float col[3],ImGuiColorEditFlags flags);
extern int GetColumnsCount();
extern bool DragInt(const char* label,int* v,float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void ImGuiIO_AddMouseButtonEvent(ImGuiIO* self,int button,bool down);
extern bool ColorButton(const char* desc_id,const ImVec4 col,ImGuiColorEditFlags flags,const ImVec2 size);
extern bool IsItemActivated();
extern bool DragFloat3(const char* label,float v[3],float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard);
extern void Render();
extern void SetTabItemClosed(const char* tab_or_docked_window_label);
extern void ImDrawList_AddTriangleFilled(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,ImU32 col);
extern void ImFontAtlas_ClearFonts(ImFontAtlas* self);
extern void PushTextWrapPos(float wrap_local_pos_x);
extern float GetFrameHeight();
extern ImGuiStorage* GetStateStorage();
extern void ImGuiStorage_Clear(ImGuiStorage* self);
extern bool DragFloat(const char* label,float* v,float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern bool DragScalar(const char* label,ImGuiDataType data_type,void* p_data,float v_speed,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern void ImDrawListSplitter_Clear(ImDrawListSplitter* self);
extern void ImGuiIO_ClearInputKeys(ImGuiIO* self);
extern bool* ImGuiStorage_GetBoolRef(ImGuiStorage* self,ImGuiID key,bool default_val);
extern void SetNextWindowSizeConstraints(const ImVec2 size_min,const ImVec2 size_max,ImGuiSizeCallback custom_callback,void* custom_callback_data);
extern float GetTextLineHeightWithSpacing();
extern bool InputScalarN(const char* label,ImGuiDataType data_type,void* p_data,int components,const void* p_step,const void* p_step_fast,const char* format,ImGuiInputTextFlags flags);
extern void SetColumnOffset(int column_index,float offset_x);
extern bool IsMouseHoveringRect(const ImVec2 r_min,const ImVec2 r_max,bool clip);
extern void ImDrawList_AddImageRounded(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p_min,const ImVec2 p_max,const ImVec2 uv_min,const ImVec2 uv_max,ImU32 col,float rounding,ImDrawFlags flags);
extern int GetColumnIndex();
extern void ImDrawList_PushTextureID(ImDrawList* self,ImTextureID texture_id);
extern void ImFont_RenderChar(ImFont* self,ImDrawList* draw_list,float size,const ImVec2 pos,ImU32 col,ImWchar c);
extern bool BeginCombo(const char* label,const char* preview_value,ImGuiComboFlags flags);
extern void GetItemRectMax(ImVec2 *pOut);
extern bool InputFloat(const char* label,float* v,float step,float step_fast,const char* format,ImGuiInputTextFlags flags);
extern void CloseCurrentPopup();
extern bool IsMouseClicked(ImGuiMouseButton button,bool repeat);
extern void ShowDemoWindow(bool* p_open);
extern void ShowMetricsWindow(bool* p_open);
extern void End();
extern void ImGuiListClipper_ForceDisplayRangeByIndices(ImGuiListClipper* self,int item_min,int item_max);
extern void PushButtonRepeat(bool repeat);
extern bool IsMouseReleased(ImGuiMouseButton button);
extern ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ImFontGlyphRangesBuilder();
extern ImGuiOnceUponAFrame* ImGuiOnceUponAFrame_ImGuiOnceUponAFrame();
extern void ImDrawList_AddBezierCubic(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col,float thickness,int num_segments);
extern bool VSliderScalar(const char* label,const ImVec2 size,ImGuiDataType data_type,void* p_data,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern void TableSetBgColor(ImGuiTableBgTarget target,ImU32 color,int column_n);
extern void DebugTextEncoding(const char* text);
extern void SetCursorScreenPos(const ImVec2 pos);
extern bool ColorEdit3(const char* label,float col[3],ImGuiColorEditFlags flags);
extern void ImGuiIO_AddMousePosEvent(ImGuiIO* self,float x,float y);
extern float GetColumnWidth(int column_index);
extern void ImGuiStorage_SetAllInt(ImGuiStorage* self,int val);
extern void PopItemWidth();
extern void ImFontAtlas_ClearTexData(ImFontAtlas* self);
extern void ShowStyleEditor(ImGuiStyle* ref);
extern void ImDrawList_PushClipRect(ImDrawList* self,const ImVec2 clip_rect_min,const ImVec2 clip_rect_max,bool intersect_with_current_clip_rect);
extern void GetWindowContentRegionMax(ImVec2 *pOut);
extern bool IsItemDeactivated();
extern bool ImFontAtlas_GetMouseCursorTexData(ImFontAtlas* self,ImGuiMouseCursor cursor,ImVec2* out_offset,ImVec2* out_size,ImVec2 out_uv_border[2],ImVec2 out_uv_fill[2]);
extern ImFontAtlasCustomRect* ImFontAtlas_GetCustomRectByIndex(ImFontAtlas* self,int index);
extern void ImGuiIO_AddInputCharacterUTF16(ImGuiIO* self,ImWchar16 c);
extern void SetColorEditOptions(ImGuiColorEditFlags flags);
extern ImGuiContext* CreateContext(ImFontAtlas* shared_font_atlas);
extern void TableNextRow(ImGuiTableRowFlags row_flags,float min_row_height);
extern void LogToFile(int auto_open_depth,const char* filename);
extern void PopFont();
extern void TableSetupScrollFreeze(int cols,int rows);
extern ImGuiMouseCursor GetMouseCursor();
extern void PopStyleVar(int count);
extern void ImGuiIO_ClearInputCharacters(ImGuiIO* self);
extern bool InputScalar(const char* label,ImGuiDataType data_type,void* p_data,const void* p_step,const void* p_step_fast,const char* format,ImGuiInputTextFlags flags);
extern ImFont* ImFontAtlas_AddFont(ImFontAtlas* self,const ImFontConfig* font_cfg);
extern bool IsWindowDocked();
extern void ImGuiPayload_Clear(ImGuiPayload* self);
extern float CalcItemWidth();
extern void GetItemRectMin(ImVec2 *pOut);
extern void ImGuiTextFilter_Clear(ImGuiTextFilter* self);
extern bool IsKeyReleased(ImGuiKey key);
extern void StyleColorsDark(ImGuiStyle* dst);
extern void ImDrawList_AddNgonFilled(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments);
extern void EndTable();
extern ImFont* ImFontAtlas_AddFontFromMemoryTTF(ImFontAtlas* self,void* font_data,int font_size,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern void ImFont_GrowIndex(ImFont* self,int new_size);
extern void ImDrawList_PathLineToMergeDuplicate(ImDrawList* self,const ImVec2 pos);
extern bool BeginTabBar(const char* str_id,ImGuiTabBarFlags flags);
extern void ImDrawList_AddCallback(ImDrawList* self,ImDrawCallback callback,void* callback_data);
extern void ImDrawList_PathBezierCubicCurveTo(ImDrawList* self,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,int num_segments);
extern void SetMouseCursor(ImGuiMouseCursor cursor_type);
extern void ImDrawList_ChannelsSplit(ImDrawList* self,int count);
extern void AlignTextToFramePadding();
extern int TableGetColumnCount();
extern void* ImGuiStorage_GetVoidPtr(ImGuiStorage* self,ImGuiID key);
extern void ImGuiIO_SetKeyEventNativeData(ImGuiIO* self,ImGuiKey key,int native_keycode,int native_scancode,int native_legacy_index);
extern ImGuiViewport* FindViewportByID(ImGuiID id);
extern bool DragScalarN(const char* label,ImGuiDataType data_type,void* p_data,int components,float v_speed,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern float GetWindowHeight();
extern void Unindent(float indent_w);
extern ImDrawList* ImDrawList_CloneOutput(ImDrawList* self);
extern void SetNextFrameWantCaptureMouse(bool want_capture_mouse);
extern float GetScrollMaxY();
extern void ImDrawListSplitter_SetCurrentChannel(ImDrawListSplitter* self,ImDrawList* draw_list,int channel_idx);
extern bool DragFloat4(const char* label,float v[4],float v_speed,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void GetContentRegionAvail(ImVec2 *pOut);
extern const char* SaveIniSettingsToMemory(size_t* out_ini_size);
extern void SetItemDefaultFocus();
extern bool SliderFloat(const char* label,float* v,float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void ImDrawList_PrimRectUV(ImDrawList* self,const ImVec2 a,const ImVec2 b,const ImVec2 uv_a,const ImVec2 uv_b,ImU32 col);
extern bool Begin(const char* name,bool* p_open,ImGuiWindowFlags flags);
extern bool InputFloat4(const char* label,float v[4],const char* format,ImGuiInputTextFlags flags);
extern void GetWindowSize(ImVec2 *pOut);
extern void ImGuiIO_AddKeyAnalogEvent(ImGuiIO* self,ImGuiKey key,bool down,float v);
extern void ImColor_SetHSV(ImColor* self,float h,float s,float v,float a);
extern void SetNextWindowPos(const ImVec2 pos,ImGuiCond cond,const ImVec2 pivot);
extern void SetScrollHereX(float center_x_ratio);
extern void SetNextWindowClass(const ImGuiWindowClass* window_class);
extern ImDrawData* GetDrawData();
extern float GetScrollX();
extern void ImDrawData_Clear(ImDrawData* self);
extern void ImDrawList_AddCircle(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments,float thickness);
extern void ImGuiIO_SetAppAcceptingEvents(ImGuiIO* self,bool accepting_events);
extern ImGuiStyle* GetStyle();
extern void PopClipRect();
extern void ImDrawList_PrimWriteVtx(ImDrawList* self,const ImVec2 pos,const ImVec2 uv,ImU32 col);
extern void ImGuiInputTextCallbackData_InsertChars(ImGuiInputTextCallbackData* self,int pos,const char* text,const char* text_end);
extern ImGuiPlatformIO* GetPlatformIO();
extern double GetTime();
extern void LogToClipboard(int auto_open_depth);
extern void SetItemAllowOverlap();
extern int TableGetRowIndex();
extern void ImDrawList_PathRect(ImDrawList* self,const ImVec2 rect_min,const ImVec2 rect_max,float rounding,ImDrawFlags flags);
extern void ImGuiIO_AddFocusEvent(ImGuiIO* self,bool focused);
extern bool ImGuiListClipper_Step(ImGuiListClipper* self);
extern bool TabItemButton(const char* label,ImGuiTabItemFlags flags);
extern void ImDrawList_AddPolyline(ImDrawList* self,const ImVec2* points,int num_points,ImU32 col,ImDrawFlags flags,float thickness);
extern void ImDrawList_PathArcTo(ImDrawList* self,const ImVec2 center,float radius,float a_min,float a_max,int num_segments);
extern ImDrawListSharedData* GetDrawListSharedData();
extern void EndListBox();
extern void EndPopup();
extern float GetFrameHeightWithSpacing();
extern bool SliderAngle(const char* label,float* v_rad,float v_degrees_min,float v_degrees_max,const char* format,ImGuiSliderFlags flags);
extern void SetKeyboardFocusHere(int offset);
extern bool ImGuiPayload_IsPreview(ImGuiPayload* self);
extern bool BeginPopup(const char* str_id,ImGuiWindowFlags flags);
extern int GetFrameCount();
extern ImFontConfig* ImFontConf_ImFontConfig();
extern float GetTreeNodeToLabelSpacing();
extern void LogFinish();
extern bool InputTextWithHint(const char* label,const char* hint,char* buf,size_t buf_size,ImGuiInputTextFlags flags,ImGuiInputTextCallback callback,void* user_data);
extern void ImDrawList_PrimRect(ImDrawList* self,const ImVec2 a,const ImVec2 b,ImU32 col);
extern void ImGuiListClipper_Begin(ImGuiListClipper* self,int items_count,float items_height);
extern void EndDisabled();
extern ImFont* ImFontAtlas_AddFontDefault(ImFontAtlas* self,const ImFontConfig* font_cfg);
extern void SetNextWindowContentSize(const ImVec2 size);
extern void ImDrawList_ChannelsSetCurrent(ImDrawList* self,int n);
extern bool IsKeyDown(ImGuiKey key);
extern void ImGuiIO_AddMouseWheelEvent(ImGuiIO* self,float wh_x,float wh_y);
extern bool BeginTabItem(const char* label,bool* p_open,ImGuiTabItemFlags flags);
extern bool ImGuiTextFilter_IsActive(ImGuiTextFilter* self);
extern const ImWchar* ImFontAtlas_GetGlyphRangesCyrillic(ImFontAtlas* self);
extern void EndTabItem();
extern bool ImGuiPayload_IsDelivery(ImGuiPayload* self);
extern bool BeginMenu(const char* label,bool enabled);
extern ImGuiPayload* ImGuiPayload_ImGuiPayload();
extern void ImGuiStorage_SetVoidPtr(ImGuiStorage* self,ImGuiID key,void* val);
extern void EndChildFrame();
extern void ResetMouseDragDelta(ImGuiMouseButton button);
extern ImFont* ImFontAtlas_AddFontFromMemoryCompressedBase85TTF(ImFontAtlas* self,const char* compressed_font_data_base85,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern const char* ImFont_CalcWordWrapPositionA(ImFont* self,float scale,const char* text,const char* text_end,float wrap_width);
extern const char* ImGuiTextBuffer_c_str(ImGuiTextBuffer* self);
extern void ImGuiViewport_GetWorkCenter(ImVec2 *pOut,ImGuiViewport* self);
extern float GetWindowDpiScale();
extern void ImDrawList_PathStroke(ImDrawList* self,ImU32 col,ImDrawFlags flags,float thickness);
extern void SetNextWindowBgAlpha(float alpha);
extern void ImDrawList_AddCircleFilled(ImDrawList* self,const ImVec2 center,float radius,ImU32 col,int num_segments);
extern ImFontAtlasCustomRect* ImFontAtlasCustomRect_ImFontAtlasCustomRect();
extern void ImGuiListClipper_End(ImGuiListClipper* self);
extern int GetMouseClickedCount(ImGuiMouseButton button);
extern void ImGuiStorage_SetBool(ImGuiStorage* self,ImGuiID key,bool val);
extern bool IsMouseDragging(ImGuiMouseButton button,float lock_threshold);
extern bool SliderFloat3(const char* label,float v[3],float v_min,float v_max,const char* format,ImGuiSliderFlags flags);
extern void ImDrawList_AddQuadFilled(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col);
extern bool DragIntRange2(const char* label,int* v_current_min,int* v_current_max,float v_speed,int v_min,int v_max,const char* format,const char* format_max,ImGuiSliderFlags flags);
extern ImGuiWindowClass* ImGuiWindowClass_ImGuiWindowClass();
extern bool IsAnyItemFocused();
extern void ImDrawList_AddRect(ImDrawList* self,const ImVec2 p_min,const ImVec2 p_max,ImU32 col,float rounding,ImDrawFlags flags,float thickness);
extern void ImDrawList_PathClear(ImDrawList* self);
extern bool SliderInt2(const char* label,int v[2],int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void StyleColorsClassic(ImGuiStyle* dst);
extern const ImWchar* ImFontAtlas_GetGlyphRangesChineseFull(ImFontAtlas* self);
extern ImGuiTableSortSpecs* ImGuiTableSortSpecs_ImGuiTableSortSpecs();
extern void PopButtonRepeat();
extern void EndChild();
extern bool VSliderInt(const char* label,const ImVec2 size,int* v,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern ImFont* ImFontAtlas_AddFontFromFileTTF(ImFontAtlas* self,const char* filename,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern void BeginGroup();
extern bool ImageButton(const char* str_id,ImTextureID user_texture_id,const ImVec2 size,const ImVec2 uv0,const ImVec2 uv1,const ImVec4 bg_col,const ImVec4 tint_col);
extern void TableSetupColumn(const char* label,ImGuiTableColumnFlags flags,float init_width_or_weight,ImGuiID user_id);
extern void PushItemWidth(float item_width);
extern const ImGuiPayload* AcceptDragDropPayload(const char* type,ImGuiDragDropFlags flags);
extern bool IsMouseDoubleClicked(ImGuiMouseButton button);
extern ImFontAtlas* ImFontAtlas_ImFontAtlas();
extern float GetTextLineHeight();
extern const ImWchar* ImFontAtlas_GetGlyphRangesThai(ImFontAtlas* self);
extern ImGuiTableSortSpecs* TableGetSortSpecs();
extern bool TableSetColumnIndex(int column_n);
extern void ImDrawListSplitter_Merge(ImDrawListSplitter* self,ImDrawList* draw_list);
extern void ImFontGlyphRangesBuilder_Clear(ImFontGlyphRangesBuilder* self);
extern bool SliderScalarN(const char* label,ImGuiDataType data_type,void* p_data,int components,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern ImGuiTextFilter* ImGuiTextFilter_ImGuiTextFilter(const char* default_filter);
extern bool ImGuiTextFilter_PassFilter(ImGuiTextFilter* self,const char* text,const char* text_end);
extern void ImGuiStorage_BuildSortByKey(ImGuiStorage* self);
extern void BeginTooltip();
extern int GetKeyIndex(ImGuiKey key);
extern float ImFont_GetCharAdvance(ImFont* self,ImWchar c);
extern ImGuiIO* GetIO();
extern void SetNextWindowSize(const ImVec2 size,ImGuiCond cond);
extern void SetNextWindowViewport(ImGuiID viewport_id);
extern bool ShowStyleSelector(const char* label);
extern const char* GetClipboardText();
extern void CalcTextSize(ImVec2 *pOut,const char* text,const char* text_end,bool hide_text_after_double_hash,float wrap_width);
extern void ImFontGlyphRangesBuilder_SetBit(ImFontGlyphRangesBuilder* self,size_t n);
extern void EndTooltip();
extern void GetCursorStartPos(ImVec2 *pOut);
extern void NextColumn();
extern ImFont* ImFontAtlas_AddFontFromMemoryCompressedTTF(ImFontAtlas* self,const void* compressed_font_data,int compressed_font_size,float size_pixels,const ImFontConfig* font_cfg,const ImWchar* glyph_ranges);
extern bool InputDouble(const char* label,double* v,double step,double step_fast,const char* format,ImGuiInputTextFlags flags);
extern ImGuiTableColumnFlags TableGetColumnFlags(int column_n);
extern void ImFont_CalcTextSizeA(ImVec2 *pOut,ImFont* self,float size,float max_width,float wrap_width,const char* text_begin,const char* text_end,const char** remaining);
extern void ImGuiIO_AddInputCharactersUTF8(ImGuiIO* self,const char* str);
extern bool ImGuiTextFilter_Draw(ImGuiTextFilter* self,const char* label,float width);
extern ImDrawList* ImDrawList_ImDrawList(const ImDrawListSharedData* shared_data);
extern void Image(ImTextureID user_texture_id,const ImVec2 size,const ImVec2 uv0,const ImVec2 uv1,const ImVec4 tint_col,const ImVec4 border_col);
extern void Bullet();
extern void EndMenu();
extern void ImFontAtlas_ClearInputData(ImFontAtlas* self);
extern ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ImGuiInputTextCallbackData();
extern float ImGuiStorage_GetFloat(ImGuiStorage* self,ImGuiID key,float default_val);
extern ImFont* GetFont();
extern bool IsMouseDown(ImGuiMouseButton button);
extern bool BeginPopupContextItem(const char* str_id,ImGuiPopupFlags popup_flags);
extern void ImColor_HSV(ImColor *pOut,float h,float s,float v,float a);
extern void EndCombo();
extern ImGuiTextBuffer* ImGuiTextBuffer_ImGuiTextBuffer();
extern void ImFontAtlas_CalcCustomRectUV(ImFontAtlas* self,const ImFontAtlasCustomRect* rect,ImVec2* out_uv_min,ImVec2* out_uv_max);
extern void LogButtons();
extern void GetMousePosOnOpeningCurrentPopup(ImVec2 *pOut);
extern void LoadIniSettingsFromDisk(const char* ini_filename);
extern const ImGuiPayload* GetDragDropPayload();
extern bool DragInt2(const char* label,int v[2],float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void EndDragDropTarget();
extern void EndMenuBar();
extern void ProgressBar(float fraction,const ImVec2 size_arg,const char* overlay);
extern bool InputText(const char* label,char* buf,size_t buf_size,ImGuiInputTextFlags flags,ImGuiInputTextCallback callback,void* user_data);
extern void SetScrollHereY(float center_y_ratio);
extern bool IsItemHovered(ImGuiHoveredFlags flags);
extern void Dummy(const ImVec2 size);
extern int* ImGuiStorage_GetIntRef(ImGuiStorage* self,ImGuiID key,int default_val);
extern void ShowUserGuide();
extern bool InputInt(const char* label,int* v,int step,int step_fast,ImGuiInputTextFlags flags);
extern void ImDrawList_PopClipRect(ImDrawList* self);
extern ImGuiPlatformMonitor* ImGuiPlatformMonitor_ImGuiPlatformMonitor();
extern bool ImGuiInputTextCallbackData_HasSelection(ImGuiInputTextCallbackData* self);
extern void ImDrawList_AddLine(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,ImU32 col,float thickness);
extern bool InputTextMultiline(const char* label,char* buf,size_t buf_size,const ImVec2 size,ImGuiInputTextFlags flags,ImGuiInputTextCallback callback,void* user_data);
extern float GetScrollY();
extern bool IsItemDeactivatedAfterEdit();
extern void ImDrawList_AddImageQuad(ImDrawList* self,ImTextureID user_texture_id,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,const ImVec2 uv1,const ImVec2 uv2,const ImVec2 uv3,const ImVec2 uv4,ImU32 col);
extern void ImGuiIO_AddInputCharacter(ImGuiIO* self,unsigned int c);
extern bool BeginDragDropSource(ImGuiDragDropFlags flags);
extern bool ColorEdit4(const char* label,float col[4],ImGuiColorEditFlags flags);
extern bool IsItemClicked(ImGuiMouseButton mouse_button);
extern float GetColumnOffset(int column_index);
extern void GetCursorPos(ImVec2 *pOut);
extern void MemFree(void* ptr);
extern ImGuiContext* GetCurrentContext();
extern void ImDrawList_AddQuad(ImDrawList* self,const ImVec2 p1,const ImVec2 p2,const ImVec2 p3,const ImVec2 p4,ImU32 col,float thickness);
extern void SetStateStorage(ImGuiStorage* storage);
extern void SetCursorPos(const ImVec2 local_pos);
extern bool ImFontAtlas_IsBuilt(ImFontAtlas* self);
extern bool BeginDragDropTarget();
extern bool ImFontAtlasCustomRect_IsPacked(ImFontAtlasCustomRect* self);
extern void ShowStackToolWindow(bool* p_open);
extern float* ImGuiStorage_GetFloatRef(ImGuiStorage* self,ImGuiID key,float default_val);
extern void PopTextWrapPos();
extern bool SliderInt3(const char* label,int v[3],int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern void ImFontGlyphRangesBuilder_AddText(ImFontGlyphRangesBuilder* self,const char* text,const char* text_end);
extern bool InputFloat3(const char* label,float v[3],const char* format,ImGuiInputTextFlags flags);
extern void SetWindowFontScale(float scale);
extern void GetCursorScreenPos(ImVec2 *pOut);
extern void ImDrawListSplitter_ClearFreeMemory(ImDrawListSplitter* self);
extern void PushFont(ImFont* font);
extern bool IsWindowAppearing();
extern bool ImGuiPayload_IsDataType(ImGuiPayload* self,const char* type);
extern bool ArrowButton(const char* str_id,ImGuiDir dir);
extern void Spacing();
extern void Columns(int count,const char* id,bool border);
extern void ImFont_AddGlyph(ImFont* self,const ImFontConfig* src_cfg,ImWchar c,float x0,float y0,float x1,float y1,float u0,float v0,float u1,float v1,float advance_x);
extern void TableHeadersRow();
extern void LogToTTY(int auto_open_depth);
extern bool IsAnyItemHovered();
extern void ImDrawList_PrimWriteIdx(ImDrawList* self,ImDrawIdx idx);
extern void GetContentRegionMax(ImVec2 *pOut);
extern ImGuiID DockSpaceOverViewport(const ImGuiViewport* viewport,ImGuiDockNodeFlags flags,const ImGuiWindowClass* window_class);
extern void SetNextItemWidth(float item_width);
extern void GetWindowPos(ImVec2 *pOut);
extern void PopAllowKeyboardFocus();
extern void GetItemRectSize(ImVec2 *pOut);
extern int ImFontAtlas_AddCustomRectFontGlyph(ImFontAtlas* self,ImFont* font,ImWchar id,int width,int height,float advance_x,const ImVec2 offset);
extern void TreePop();
extern void ImGuiIO_AddKeyEvent(ImGuiIO* self,ImGuiKey key,bool down);
extern void ImGuiStorage_SetInt(ImGuiStorage* self,ImGuiID key,int val);
extern void ImDrawList_GetClipRectMax(ImVec2 *pOut,ImDrawList* self);
extern void ImFontAtlas_GetTexDataAsAlpha8(ImFontAtlas* self,unsigned char** out_pixels,int* out_width,int* out_height,int* out_bytes_per_pixel);
extern void ImFont_ClearOutputData(ImFont* self);
extern void NewFrame();
extern void ImDrawList_PopTextureID(ImDrawList* self);
extern bool ImGuiStorage_GetBool(ImGuiStorage* self,ImGuiID key,bool default_val);
extern bool BeginPopupContextWindow(const char* str_id,ImGuiPopupFlags popup_flags);
extern void ColorConvertHSVtoRGB(float h,float s,float v,float* out_r,float* out_g,float* out_b);
extern bool DragInt3(const char* label,int v[3],float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
extern bool InputInt3(const char* label,int v[3],ImGuiInputTextFlags flags);
extern void ImFont_AddRemapChar(ImFont* self,ImWchar dst,ImWchar src,bool overwrite_dst);
extern void ImFont_SetGlyphVisible(ImFont* self,ImWchar c,bool visible);
extern const char* GetKeyName(ImGuiKey key);
extern void ImFontGlyphRangesBuilder_BuildRanges(ImFontGlyphRangesBuilder* self,ImVector_ImWchar* out_ranges);
extern void OpenPopupOnItemClick(const char* str_id,ImGuiPopupFlags popup_flags);
extern void SaveIniSettingsToDisk(const char* ini_filename);
extern void Separator();
extern bool SliderScalar(const char* label,ImGuiDataType data_type,void* p_data,const void* p_min,const void* p_max,const char* format,ImGuiSliderFlags flags);
extern void RenderPlatformWindowsDefault(void* platform_render_arg,void* renderer_render_arg);
extern bool IsItemEdited();
extern void ShowDebugLogWindow(bool* p_open);
extern void ImDrawList_PrimQuadUV(ImDrawList* self,const ImVec2 a,const ImVec2 b,const ImVec2 c,const ImVec2 d,const ImVec2 uv_a,const ImVec2 uv_b,const ImVec2 uv_c,const ImVec2 uv_d,ImU32 col);
extern bool InputInt2(const char* label,int v[2],ImGuiInputTextFlags flags);
extern bool InputInt4(const char* label,int v[4],ImGuiInputTextFlags flags);
extern bool IsItemToggledOpen();
extern void TableHeader(const char* label);
extern void TableSetColumnEnabled(int column_n,bool v);
extern void ImDrawList_ChannelsMerge(ImDrawList* self);
extern ImGuiViewport* FindViewportByPlatformHandle(void* platform_handle);
extern void SetCursorPosY(float local_y);
extern ImGuiViewport* GetWindowViewport();
extern float GetCursorPosY();
extern const char* GetStyleColorName(ImGuiCol idx);
extern void PushClipRect(const ImVec2 clip_rect_min,const ImVec2 clip_rect_max,bool intersect_with_current_clip_rect);
extern void DestroyPlatformWindows();
extern ImTextureID ImDrawCmd_GetTexID(ImDrawCmd* self);
extern void ImDrawList_PrimReserve(ImDrawList* self,int idx_count,int vtx_count);
extern bool ImFont_IsGlyphRangeUnused(ImFont* self,unsigned int c_begin,unsigned int c_last);
extern void EndGroup();
extern void ImFontAtlas_SetTexID(ImFontAtlas* self,ImTextureID id);
extern void EndMainMenuBar();
extern void GetFontTexUvWhitePixel(ImVec2 *pOut);
extern ImGuiPlatformImeData* ImGuiPlatformImeData_ImGuiPlatformImeData();
extern bool IsWindowHovered(ImGuiHoveredFlags flags);
extern void ImGuiInputTextCallbackData_ClearSelection(ImGuiInputTextCallbackData* self);
extern void GetMouseDragDelta(ImVec2 *pOut,ImGuiMouseButton button,float lock_threshold);
extern void SetNextWindowCollapsed(bool collapsed,ImGuiCond cond);
extern ImU32 ColorConvertFloat4ToU32(const ImVec4 in);
extern bool ColorPicker4(const char* label,float col[4],ImGuiColorEditFlags flags,const float* ref_col);

#ifdef __cplusplus
}
#endif
