// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package imgui

// original name: EmphasisState
type EmphasisState int32

const (
	NONE   = 0
	LEFT   = 1
	MIDDLE = 2
	RIGHT  = 3
)

// original name: LinkState
type LinkState int32

const (
	NOLINK                            = 0
	HASSQUAREBRACKETOPEN              = 1
	HASSQUAREBRACKETS                 = 2
	HASSQUAREBRACKETSROUNDBRACKETOPEN = 3
)

// original name: MarkdownFormatType
type MarkdownFormatType int32

const (
	NORMALTEXT    = 0
	HEADING       = 1
	UNORDEREDLIST = 2
	LINK          = 3
	EMPHASIS      = 4
)
