// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package imgui

// original name: ImAxis_
type PlotAxisEnum int32

const (
	AxisX1    PlotAxisEnum = 0
	AxisX2    PlotAxisEnum = 1
	AxisX3    PlotAxisEnum = 2
	AxisY1    PlotAxisEnum = 3
	AxisY2    PlotAxisEnum = 4
	AxisY3    PlotAxisEnum = 5
	AxisCOUNT PlotAxisEnum = 6
)

// original name: ImPlotAxisFlags_
type PlotAxisFlags int32

const (
	PlotAxisFlagsNone          PlotAxisFlags = 0
	PlotAxisFlagsNoLabel       PlotAxisFlags = 1
	PlotAxisFlagsNoGridLines   PlotAxisFlags = 2
	PlotAxisFlagsNoTickMarks   PlotAxisFlags = 4
	PlotAxisFlagsNoTickLabels  PlotAxisFlags = 8
	PlotAxisFlagsNoInitialFit  PlotAxisFlags = 16
	PlotAxisFlagsNoMenus       PlotAxisFlags = 32
	PlotAxisFlagsNoSideSwitch  PlotAxisFlags = 64
	PlotAxisFlagsNoHighlight   PlotAxisFlags = 128
	PlotAxisFlagsOpposite      PlotAxisFlags = 256
	PlotAxisFlagsForeground    PlotAxisFlags = 512
	PlotAxisFlagsInvert        PlotAxisFlags = 1024
	PlotAxisFlagsAutoFit       PlotAxisFlags = 2048
	PlotAxisFlagsRangeFit      PlotAxisFlags = 4096
	PlotAxisFlagsPanStretch    PlotAxisFlags = 8192
	PlotAxisFlagsLockMin       PlotAxisFlags = 16384
	PlotAxisFlagsLockMax       PlotAxisFlags = 32768
	PlotAxisFlagsLock          PlotAxisFlags = 49152
	PlotAxisFlagsNoDecorations PlotAxisFlags = 15
	PlotAxisFlagsAuxDefault    PlotAxisFlags = 258
)

// original name: ImPlotBarGroupsFlags_
type PlotBarGroupsFlags int32

const (
	PlotBarGroupsFlagsNone       PlotBarGroupsFlags = 0
	PlotBarGroupsFlagsHorizontal PlotBarGroupsFlags = 1024
	PlotBarGroupsFlagsStacked    PlotBarGroupsFlags = 2048
)

// original name: ImPlotBarsFlags_
type PlotBarsFlags int32

const (
	PlotBarsFlagsNone       PlotBarsFlags = 0
	PlotBarsFlagsHorizontal PlotBarsFlags = 1024
)

// original name: ImPlotBin_
type PlotBin int32

const (
	PlotBinSqrt    PlotBin = -1
	PlotBinSturges PlotBin = -2
	PlotBinRice    PlotBin = -3
	PlotBinScott   PlotBin = -4
)

// original name: ImPlotCol_
type PlotCol int32

const (
	PlotColLine          PlotCol = 0
	PlotColFill          PlotCol = 1
	PlotColMarkerOutline PlotCol = 2
	PlotColMarkerFill    PlotCol = 3
	PlotColErrorBar      PlotCol = 4
	PlotColFrameBg       PlotCol = 5
	PlotColPlotBg        PlotCol = 6
	PlotColPlotBorder    PlotCol = 7
	PlotColLegendBg      PlotCol = 8
	PlotColLegendBorder  PlotCol = 9
	PlotColLegendText    PlotCol = 10
	PlotColTitleText     PlotCol = 11
	PlotColInlayText     PlotCol = 12
	PlotColAxisText      PlotCol = 13
	PlotColAxisGrid      PlotCol = 14
	PlotColAxisTick      PlotCol = 15
	PlotColAxisBg        PlotCol = 16
	PlotColAxisBgHovered PlotCol = 17
	PlotColAxisBgActive  PlotCol = 18
	PlotColSelection     PlotCol = 19
	PlotColCrosshairs    PlotCol = 20
	PlotColCOUNT         PlotCol = 21
)

// original name: ImPlotColormapScaleFlags_
type PlotColormapScaleFlags int32

const (
	PlotColormapScaleFlagsNone     PlotColormapScaleFlags = 0
	PlotColormapScaleFlagsNoLabel  PlotColormapScaleFlags = 1
	PlotColormapScaleFlagsOpposite PlotColormapScaleFlags = 2
	PlotColormapScaleFlagsInvert   PlotColormapScaleFlags = 4
)

// original name: ImPlotColormap_
type PlotColormap int32

const (
	PlotColormapDeep     PlotColormap = 0
	PlotColormapDark     PlotColormap = 1
	PlotColormapPastel   PlotColormap = 2
	PlotColormapPaired   PlotColormap = 3
	PlotColormapViridis  PlotColormap = 4
	PlotColormapPlasma   PlotColormap = 5
	PlotColormapHot      PlotColormap = 6
	PlotColormapCool     PlotColormap = 7
	PlotColormapPink     PlotColormap = 8
	PlotColormapJet      PlotColormap = 9
	PlotColormapTwilight PlotColormap = 10
	PlotColormapRdBu     PlotColormap = 11
	PlotColormapBrBG     PlotColormap = 12
	PlotColormapPiYG     PlotColormap = 13
	PlotColormapSpectral PlotColormap = 14
	PlotColormapGreys    PlotColormap = 15
)

// original name: ImPlotCond_
type PlotCond int32

const (
	PlotCondNone   PlotCond = 0
	PlotCondAlways PlotCond = 1
	PlotCondOnce   PlotCond = 2
)

// original name: ImPlotDateFmt_
type PlotDateFmt int32

const (
	PlotDateFmtNone    PlotDateFmt = 0
	PlotDateFmtDayMo   PlotDateFmt = 1
	PlotDateFmtDayMoYr PlotDateFmt = 2
	PlotDateFmtMoYr    PlotDateFmt = 3
	PlotDateFmtMo      PlotDateFmt = 4
	PlotDateFmtYr      PlotDateFmt = 5
)

// original name: ImPlotDigitalFlags_
type PlotDigitalFlags int32

const (
	PlotDigitalFlagsNone PlotDigitalFlags = 0
)

// original name: ImPlotDragToolFlags_
type PlotDragToolFlags int32

const (
	PlotDragToolFlagsNone      PlotDragToolFlags = 0
	PlotDragToolFlagsNoCursors PlotDragToolFlags = 1
	PlotDragToolFlagsNoFit     PlotDragToolFlags = 2
	PlotDragToolFlagsNoInputs  PlotDragToolFlags = 4
	PlotDragToolFlagsDelayed   PlotDragToolFlags = 8
)

// original name: ImPlotDummyFlags_
type PlotDummyFlags int32

const (
	PlotDummyFlagsNone PlotDummyFlags = 0
)

// original name: ImPlotErrorBarsFlags_
type PlotErrorBarsFlags int32

const (
	PlotErrorBarsFlagsNone       PlotErrorBarsFlags = 0
	PlotErrorBarsFlagsHorizontal PlotErrorBarsFlags = 1024
)

// original name: ImPlotFlags_
type PlotFlags int32

const (
	PlotFlagsNone        PlotFlags = 0
	PlotFlagsNoTitle     PlotFlags = 1
	PlotFlagsNoLegend    PlotFlags = 2
	PlotFlagsNoMouseText PlotFlags = 4
	PlotFlagsNoInputs    PlotFlags = 8
	PlotFlagsNoMenus     PlotFlags = 16
	PlotFlagsNoBoxSelect PlotFlags = 32
	PlotFlagsNoFrame     PlotFlags = 64
	PlotFlagsEqual       PlotFlags = 128
	PlotFlagsCrosshairs  PlotFlags = 256
	PlotFlagsCanvasOnly  PlotFlags = 55
)

// original name: ImPlotHeatmapFlags_
type PlotHeatmapFlags int32

const (
	PlotHeatmapFlagsNone     PlotHeatmapFlags = 0
	PlotHeatmapFlagsColMajor PlotHeatmapFlags = 1024
)

// original name: ImPlotHistogramFlags_
type PlotHistogramFlags int32

const (
	PlotHistogramFlagsNone       PlotHistogramFlags = 0
	PlotHistogramFlagsHorizontal PlotHistogramFlags = 1024
	PlotHistogramFlagsCumulative PlotHistogramFlags = 2048
	PlotHistogramFlagsDensity    PlotHistogramFlags = 4096
	PlotHistogramFlagsNoOutliers PlotHistogramFlags = 8192
	PlotHistogramFlagsColMajor   PlotHistogramFlags = 16384
)

// original name: ImPlotImageFlags_
type PlotImageFlags int32

const (
	PlotImageFlagsNone PlotImageFlags = 0
)

// original name: ImPlotInfLinesFlags_
type PlotInfLinesFlags int32

const (
	PlotInfLinesFlagsNone       PlotInfLinesFlags = 0
	PlotInfLinesFlagsHorizontal PlotInfLinesFlags = 1024
)

// original name: ImPlotItemFlags_
type PlotItemFlags int32

const (
	PlotItemFlagsNone     PlotItemFlags = 0
	PlotItemFlagsNoLegend PlotItemFlags = 1
	PlotItemFlagsNoFit    PlotItemFlags = 2
)

// original name: ImPlotLegendFlags_
type PlotLegendFlags int32

const (
	PlotLegendFlagsNone            PlotLegendFlags = 0
	PlotLegendFlagsNoButtons       PlotLegendFlags = 1
	PlotLegendFlagsNoHighlightItem PlotLegendFlags = 2
	PlotLegendFlagsNoHighlightAxis PlotLegendFlags = 4
	PlotLegendFlagsNoMenus         PlotLegendFlags = 8
	PlotLegendFlagsOutside         PlotLegendFlags = 16
	PlotLegendFlagsHorizontal      PlotLegendFlags = 32
	PlotLegendFlagsSort            PlotLegendFlags = 64
)

// original name: ImPlotLineFlags_
type PlotLineFlags int32

const (
	PlotLineFlagsNone     PlotLineFlags = 0
	PlotLineFlagsSegments PlotLineFlags = 1024
	PlotLineFlagsLoop     PlotLineFlags = 2048
	PlotLineFlagsSkipNaN  PlotLineFlags = 4096
	PlotLineFlagsNoClip   PlotLineFlags = 8192
	PlotLineFlagsShaded   PlotLineFlags = 16384
)

// original name: ImPlotLocation_
type PlotLocation int32

const (
	PlotLocationCenter    PlotLocation = 0
	PlotLocationNorth     PlotLocation = 1
	PlotLocationSouth     PlotLocation = 2
	PlotLocationWest      PlotLocation = 4
	PlotLocationEast      PlotLocation = 8
	PlotLocationNorthWest PlotLocation = 5
	PlotLocationNorthEast PlotLocation = 9
	PlotLocationSouthWest PlotLocation = 6
	PlotLocationSouthEast PlotLocation = 10
)

// original name: ImPlotMarker_
type PlotMarker int32

const (
	PlotMarkerNone     PlotMarker = -1
	PlotMarkerCircle   PlotMarker = 0
	PlotMarkerSquare   PlotMarker = 1
	PlotMarkerDiamond  PlotMarker = 2
	PlotMarkerUp       PlotMarker = 3
	PlotMarkerDown     PlotMarker = 4
	PlotMarkerLeft     PlotMarker = 5
	PlotMarkerRight    PlotMarker = 6
	PlotMarkerCross    PlotMarker = 7
	PlotMarkerPlus     PlotMarker = 8
	PlotMarkerAsterisk PlotMarker = 9
	PlotMarkerCOUNT    PlotMarker = 10
)

// original name: ImPlotMouseTextFlags_
type PlotMouseTextFlags int32

const (
	PlotMouseTextFlagsNone       PlotMouseTextFlags = 0
	PlotMouseTextFlagsNoAuxAxes  PlotMouseTextFlags = 1
	PlotMouseTextFlagsNoFormat   PlotMouseTextFlags = 2
	PlotMouseTextFlagsShowAlways PlotMouseTextFlags = 4
)

// original name: ImPlotPieChartFlags_
type PlotPieChartFlags int32

const (
	PlotPieChartFlagsNone         PlotPieChartFlags = 0
	PlotPieChartFlagsNormalize    PlotPieChartFlags = 1024
	PlotPieChartFlagsIgnoreHidden PlotPieChartFlags = 2048
)

// original name: ImPlotScale_
type PlotScale int32

const (
	PlotScaleLinear PlotScale = 0
	PlotScaleTime   PlotScale = 1
	PlotScaleLog10  PlotScale = 2
	PlotScaleSymLog PlotScale = 3
)

// original name: ImPlotScatterFlags_
type PlotScatterFlags int32

const (
	PlotScatterFlagsNone   PlotScatterFlags = 0
	PlotScatterFlagsNoClip PlotScatterFlags = 1024
)

// original name: ImPlotShadedFlags_
type PlotShadedFlags int32

const (
	PlotShadedFlagsNone PlotShadedFlags = 0
)

// original name: ImPlotStairsFlags_
type PlotStairsFlags int32

const (
	PlotStairsFlagsNone    PlotStairsFlags = 0
	PlotStairsFlagsPreStep PlotStairsFlags = 1024
	PlotStairsFlagsShaded  PlotStairsFlags = 2048
)

// original name: ImPlotStemsFlags_
type PlotStemsFlags int32

const (
	PlotStemsFlagsNone       PlotStemsFlags = 0
	PlotStemsFlagsHorizontal PlotStemsFlags = 1024
)

// original name: ImPlotStyleVar_
type PlotStyleVar int32

const (
	PlotStyleVarLineWeight         PlotStyleVar = 0
	PlotStyleVarMarker             PlotStyleVar = 1
	PlotStyleVarMarkerSize         PlotStyleVar = 2
	PlotStyleVarMarkerWeight       PlotStyleVar = 3
	PlotStyleVarFillAlpha          PlotStyleVar = 4
	PlotStyleVarErrorBarSize       PlotStyleVar = 5
	PlotStyleVarErrorBarWeight     PlotStyleVar = 6
	PlotStyleVarDigitalBitHeight   PlotStyleVar = 7
	PlotStyleVarDigitalBitGap      PlotStyleVar = 8
	PlotStyleVarPlotBorderSize     PlotStyleVar = 9
	PlotStyleVarMinorAlpha         PlotStyleVar = 10
	PlotStyleVarMajorTickLen       PlotStyleVar = 11
	PlotStyleVarMinorTickLen       PlotStyleVar = 12
	PlotStyleVarMajorTickSize      PlotStyleVar = 13
	PlotStyleVarMinorTickSize      PlotStyleVar = 14
	PlotStyleVarMajorGridSize      PlotStyleVar = 15
	PlotStyleVarMinorGridSize      PlotStyleVar = 16
	PlotStyleVarPlotPadding        PlotStyleVar = 17
	PlotStyleVarLabelPadding       PlotStyleVar = 18
	PlotStyleVarLegendPadding      PlotStyleVar = 19
	PlotStyleVarLegendInnerPadding PlotStyleVar = 20
	PlotStyleVarLegendSpacing      PlotStyleVar = 21
	PlotStyleVarMousePosPadding    PlotStyleVar = 22
	PlotStyleVarAnnotationPadding  PlotStyleVar = 23
	PlotStyleVarFitPadding         PlotStyleVar = 24
	PlotStyleVarPlotDefaultSize    PlotStyleVar = 25
	PlotStyleVarPlotMinSize        PlotStyleVar = 26
	PlotStyleVarCOUNT              PlotStyleVar = 27
)

// original name: ImPlotSubplotFlags_
type PlotSubplotFlags int32

const (
	PlotSubplotFlagsNone       PlotSubplotFlags = 0
	PlotSubplotFlagsNoTitle    PlotSubplotFlags = 1
	PlotSubplotFlagsNoLegend   PlotSubplotFlags = 2
	PlotSubplotFlagsNoMenus    PlotSubplotFlags = 4
	PlotSubplotFlagsNoResize   PlotSubplotFlags = 8
	PlotSubplotFlagsNoAlign    PlotSubplotFlags = 16
	PlotSubplotFlagsShareItems PlotSubplotFlags = 32
	PlotSubplotFlagsLinkRows   PlotSubplotFlags = 64
	PlotSubplotFlagsLinkCols   PlotSubplotFlags = 128
	PlotSubplotFlagsLinkAllX   PlotSubplotFlags = 256
	PlotSubplotFlagsLinkAllY   PlotSubplotFlags = 512
	PlotSubplotFlagsColMajor   PlotSubplotFlags = 1024
)

// original name: ImPlotTextFlags_
type PlotTextFlags int32

const (
	PlotTextFlagsNone     PlotTextFlags = 0
	PlotTextFlagsVertical PlotTextFlags = 1024
)

// original name: ImPlotTimeFmt_
type PlotTimeFmt int32

const (
	PlotTimeFmtNone     PlotTimeFmt = 0
	PlotTimeFmtUs       PlotTimeFmt = 1
	PlotTimeFmtSUs      PlotTimeFmt = 2
	PlotTimeFmtSMs      PlotTimeFmt = 3
	PlotTimeFmtS        PlotTimeFmt = 4
	PlotTimeFmtMinSMs   PlotTimeFmt = 5
	PlotTimeFmtHrMinSMs PlotTimeFmt = 6
	PlotTimeFmtHrMinS   PlotTimeFmt = 7
	PlotTimeFmtHrMin    PlotTimeFmt = 8
	PlotTimeFmtHr       PlotTimeFmt = 9
)

// original name: ImPlotTimeUnit_
type PlotTimeUnit int32

const (
	PlotTimeUnitUs    PlotTimeUnit = 0
	PlotTimeUnitMs    PlotTimeUnit = 1
	PlotTimeUnitS     PlotTimeUnit = 2
	PlotTimeUnitMin   PlotTimeUnit = 3
	PlotTimeUnitHr    PlotTimeUnit = 4
	PlotTimeUnitDay   PlotTimeUnit = 5
	PlotTimeUnitMo    PlotTimeUnit = 6
	PlotTimeUnitYr    PlotTimeUnit = 7
	PlotTimeUnitCOUNT PlotTimeUnit = 8
)
