package cimgui

// #include "cimgui_wrapper.h"
import "C"

type ImGuiTextRange C.ImGuiTextRange
type ImGuiColorMod C.ImGuiColorMod
type ImGuiSettingsHandler C.ImGuiSettingsHandler
type ImGuiStackTool C.ImGuiStackTool
type ImGuiTableCellData C.ImGuiTableCellData
type ImGuiTableColumn C.ImGuiTableColumn
type ImDrawData C.ImDrawData
type ImGuiDockContext C.ImGuiDockContext
type ImGuiWindowSettings C.ImGuiWindowSettings
type ImGuiOnceUponAFrame C.ImGuiOnceUponAFrame
type ImGuiPayload C.ImGuiPayload
type ImGuiGroupData C.ImGuiGroupData
type ImGuiInputEventMouseButton C.ImGuiInputEventMouseButton
type ImGuiInputTextState C.ImGuiInputTextState
type ImGuiOldColumnData C.ImGuiOldColumnData
type ImGuiOldColumns C.ImGuiOldColumns
type ImColor C.ImColor
type ImGuiDataTypeInfo C.ImGuiDataTypeInfo
type ImGuiSizeCallbackData C.ImGuiSizeCallbackData
type ImGuiTableSortSpecs C.ImGuiTableSortSpecs
type ImVec2ih C.ImVec2ih
type ImDrawVert C.ImDrawVert
type ImGuiListClipperData C.ImGuiListClipperData
type ImGuiNextWindowData C.ImGuiNextWindowData
type ImGuiPlatformImeData C.ImGuiPlatformImeData
type ImGuiTextBuffer C.ImGuiTextBuffer
type ImGuiDockNode C.ImGuiDockNode
type ImGuiInputEventMousePos C.ImGuiInputEventMousePos
type ImGuiLastItemData C.ImGuiLastItemData
type ImGuiPlatformMonitor C.ImGuiPlatformMonitor
type ImGuiStyleMod C.ImGuiStyleMod
type ImGuiPtrOrIndex C.ImGuiPtrOrIndex
type ImGuiShrinkWidthItem C.ImGuiShrinkWidthItem
type ImGuiTabBar C.ImGuiTabBar
type ImDrawList C.ImDrawList
type ImFont C.ImFont
type ImGuiContext C.ImGuiContext
type ImGuiInputEventAppFocused C.ImGuiInputEventAppFocused
type ImGuiInputEventKey C.ImGuiInputEventKey
type ImGuiTableColumnSettings C.ImGuiTableColumnSettings
type ImGuiTextFilter C.ImGuiTextFilter
type ImRect C.ImRect
type ImVec1 C.ImVec1
type ImGuiTableTempData C.ImGuiTableTempData
type ImDrawCmdHeader C.ImDrawCmdHeader
type ImGuiComboPreviewData C.ImGuiComboPreviewData
type ImGuiListClipper C.ImGuiListClipper
type ImGuiStackSizes C.ImGuiStackSizes
type ImGuiTableSettings C.ImGuiTableSettings
type ImGuiStackLevelInfo C.ImGuiStackLevelInfo
type ImVec4 C.ImVec4
type ImDrawChannel C.ImDrawChannel
type ImDrawCmd C.ImDrawCmd
type ImGuiIO C.ImGuiIO
type ImGuiInputEventMouseWheel C.ImGuiInputEventMouseWheel
type ImGuiNextItemData C.ImGuiNextItemData
type ImGuiViewportP C.ImGuiViewportP
type ImGuiWindowStackData C.ImGuiWindowStackData
type ImVec2 C.ImVec2
type ImFontAtlasCustomRect C.ImFontAtlasCustomRect
type ImGuiInputEventMouseViewport C.ImGuiInputEventMouseViewport
type ImGuiStoragePair C.ImGuiStoragePair
type ImGuiTable C.ImGuiTable
type ImGuiViewport C.ImGuiViewport
type ImGuiContextHook C.ImGuiContextHook
type ImGuiPopupData C.ImGuiPopupData
type ImGuiWindowDockStyle C.ImGuiWindowDockStyle
type ImGuiTabItem C.ImGuiTabItem
type ImGuiTableInstanceData C.ImGuiTableInstanceData
type ImGuiWindow C.ImGuiWindow
type ImFontAtlas C.ImFontAtlas
type ImGuiDataTypeTempStorage C.ImGuiDataTypeTempStorage
type ImGuiInputEventText C.ImGuiInputEventText
type ImGuiListClipperRange C.ImGuiListClipperRange
type ImGuiStorage C.ImGuiStorage
type ImGuiWindowTempData C.ImGuiWindowTempData
type ImDrawListSharedData C.ImDrawListSharedData
type ImFontConfig C.ImFontConfig
type ImFontGlyph C.ImFontGlyph
type ImGuiInputTextCallbackData C.ImGuiInputTextCallbackData
type ImGuiWindowClass C.ImGuiWindowClass
type ImGuiNavItemData C.ImGuiNavItemData
type ImDrawDataBuilder C.ImDrawDataBuilder
type ImFontBuilderIO C.ImFontBuilderIO
type ImGuiInputEvent C.ImGuiInputEvent
type ImGuiKeyData C.ImGuiKeyData
type ImGuiMetricsConfig C.ImGuiMetricsConfig
type ImGuiStyle C.ImGuiStyle
type ImGuiTableColumnSortSpecs C.ImGuiTableColumnSortSpecs
type ImBitVector C.ImBitVector
type ImDrawListSplitter C.ImDrawListSplitter
type ImFontGlyphRangesBuilder C.ImFontGlyphRangesBuilder
type ImGuiMenuColumns C.ImGuiMenuColumns
type ImGuiPlatformIO C.ImGuiPlatformIO
