// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package implot

// original name: ImAxis_
type AxisEnum int32

const (
	AxisX1    AxisEnum = 0
	AxisX2    AxisEnum = 1
	AxisX3    AxisEnum = 2
	AxisY1    AxisEnum = 3
	AxisY2    AxisEnum = 4
	AxisY3    AxisEnum = 5
	AxisCOUNT AxisEnum = 6
)

// original name: ImPlotAxisFlags_
type AxisFlags int32

const (
	AxisFlagsNone          AxisFlags = 0
	AxisFlagsNoLabel       AxisFlags = 1
	AxisFlagsNoGridLines   AxisFlags = 2
	AxisFlagsNoTickMarks   AxisFlags = 4
	AxisFlagsNoTickLabels  AxisFlags = 8
	AxisFlagsNoInitialFit  AxisFlags = 16
	AxisFlagsNoMenus       AxisFlags = 32
	AxisFlagsNoSideSwitch  AxisFlags = 64
	AxisFlagsNoHighlight   AxisFlags = 128
	AxisFlagsOpposite      AxisFlags = 256
	AxisFlagsForeground    AxisFlags = 512
	AxisFlagsInvert        AxisFlags = 1024
	AxisFlagsAutoFit       AxisFlags = 2048
	AxisFlagsRangeFit      AxisFlags = 4096
	AxisFlagsPanStretch    AxisFlags = 8192
	AxisFlagsLockMin       AxisFlags = 16384
	AxisFlagsLockMax       AxisFlags = 32768
	AxisFlagsLock          AxisFlags = 49152
	AxisFlagsNoDecorations AxisFlags = 15
	AxisFlagsAuxDefault    AxisFlags = 258
)

// original name: ImPlotBarGroupsFlags_
type BarGroupsFlags int32

const (
	BarGroupsFlagsNone       BarGroupsFlags = 0
	BarGroupsFlagsHorizontal BarGroupsFlags = 1024
	BarGroupsFlagsStacked    BarGroupsFlags = 2048
)

// original name: ImPlotBarsFlags_
type BarsFlags int32

const (
	BarsFlagsNone       BarsFlags = 0
	BarsFlagsHorizontal BarsFlags = 1024
)

// original name: ImPlotBin_
type Bin int32

const (
	BinSqrt    Bin = -1
	BinSturges Bin = -2
	BinRice    Bin = -3
	BinScott   Bin = -4
)

// original name: ImPlotCol_
type Col int32

const (
	ColLine          Col = 0
	ColFill          Col = 1
	ColMarkerOutline Col = 2
	ColMarkerFill    Col = 3
	ColErrorBar      Col = 4
	ColFrameBg       Col = 5
	ColPlotBg        Col = 6
	ColPlotBorder    Col = 7
	ColLegendBg      Col = 8
	ColLegendBorder  Col = 9
	ColLegendText    Col = 10
	ColTitleText     Col = 11
	ColInlayText     Col = 12
	ColAxisText      Col = 13
	ColAxisGrid      Col = 14
	ColAxisTick      Col = 15
	ColAxisBg        Col = 16
	ColAxisBgHovered Col = 17
	ColAxisBgActive  Col = 18
	ColSelection     Col = 19
	ColCrosshairs    Col = 20
	ColCOUNT         Col = 21
)

// original name: ImPlotColormapScaleFlags_
type ColormapScaleFlags int32

const (
	ColormapScaleFlagsNone     ColormapScaleFlags = 0
	ColormapScaleFlagsNoLabel  ColormapScaleFlags = 1
	ColormapScaleFlagsOpposite ColormapScaleFlags = 2
	ColormapScaleFlagsInvert   ColormapScaleFlags = 4
)

// original name: ImPlotColormap_
type Colormap int32

const (
	ColormapDeep     Colormap = 0
	ColormapDark     Colormap = 1
	ColormapPastel   Colormap = 2
	ColormapPaired   Colormap = 3
	ColormapViridis  Colormap = 4
	ColormapPlasma   Colormap = 5
	ColormapHot      Colormap = 6
	ColormapCool     Colormap = 7
	ColormapPink     Colormap = 8
	ColormapJet      Colormap = 9
	ColormapTwilight Colormap = 10
	ColormapRdBu     Colormap = 11
	ColormapBrBG     Colormap = 12
	ColormapPiYG     Colormap = 13
	ColormapSpectral Colormap = 14
	ColormapGreys    Colormap = 15
)

// original name: ImPlotCond_
type Cond int32

const (
	CondNone   Cond = 0
	CondAlways Cond = 1
	CondOnce   Cond = 2
)

// original name: ImPlotDateFmt_
type DateFmt int32

const (
	DateFmtNone    DateFmt = 0
	DateFmtDayMo   DateFmt = 1
	DateFmtDayMoYr DateFmt = 2
	DateFmtMoYr    DateFmt = 3
	DateFmtMo      DateFmt = 4
	DateFmtYr      DateFmt = 5
)

// original name: ImPlotDigitalFlags_
type DigitalFlags int32

const (
	DigitalFlagsNone DigitalFlags = 0
)

// original name: ImPlotDragToolFlags_
type DragToolFlags int32

const (
	DragToolFlagsNone      DragToolFlags = 0
	DragToolFlagsNoCursors DragToolFlags = 1
	DragToolFlagsNoFit     DragToolFlags = 2
	DragToolFlagsNoInputs  DragToolFlags = 4
	DragToolFlagsDelayed   DragToolFlags = 8
)

// original name: ImPlotDummyFlags_
type DummyFlags int32

const (
	DummyFlagsNone DummyFlags = 0
)

// original name: ImPlotErrorBarsFlags_
type ErrorBarsFlags int32

const (
	ErrorBarsFlagsNone       ErrorBarsFlags = 0
	ErrorBarsFlagsHorizontal ErrorBarsFlags = 1024
)

// original name: ImPlotFlags_
type Flags int32

const (
	FlagsNone        Flags = 0
	FlagsNoTitle     Flags = 1
	FlagsNoLegend    Flags = 2
	FlagsNoMouseText Flags = 4
	FlagsNoInputs    Flags = 8
	FlagsNoMenus     Flags = 16
	FlagsNoBoxSelect Flags = 32
	FlagsNoFrame     Flags = 64
	FlagsEqual       Flags = 128
	FlagsCrosshairs  Flags = 256
	FlagsCanvasOnly  Flags = 55
)

// original name: ImPlotHeatmapFlags_
type HeatmapFlags int32

const (
	HeatmapFlagsNone     HeatmapFlags = 0
	HeatmapFlagsColMajor HeatmapFlags = 1024
)

// original name: ImPlotHistogramFlags_
type HistogramFlags int32

const (
	HistogramFlagsNone       HistogramFlags = 0
	HistogramFlagsHorizontal HistogramFlags = 1024
	HistogramFlagsCumulative HistogramFlags = 2048
	HistogramFlagsDensity    HistogramFlags = 4096
	HistogramFlagsNoOutliers HistogramFlags = 8192
	HistogramFlagsColMajor   HistogramFlags = 16384
)

// original name: ImPlotImageFlags_
type ImageFlags int32

const (
	ImageFlagsNone ImageFlags = 0
)

// original name: ImPlotInfLinesFlags_
type InfLinesFlags int32

const (
	InfLinesFlagsNone       InfLinesFlags = 0
	InfLinesFlagsHorizontal InfLinesFlags = 1024
)

// original name: ImPlotItemFlags_
type ItemFlags int32

const (
	ItemFlagsNone     ItemFlags = 0
	ItemFlagsNoLegend ItemFlags = 1
	ItemFlagsNoFit    ItemFlags = 2
)

// original name: ImPlotLegendFlags_
type LegendFlags int32

const (
	LegendFlagsNone            LegendFlags = 0
	LegendFlagsNoButtons       LegendFlags = 1
	LegendFlagsNoHighlightItem LegendFlags = 2
	LegendFlagsNoHighlightAxis LegendFlags = 4
	LegendFlagsNoMenus         LegendFlags = 8
	LegendFlagsOutside         LegendFlags = 16
	LegendFlagsHorizontal      LegendFlags = 32
	LegendFlagsSort            LegendFlags = 64
)

// original name: ImPlotLineFlags_
type LineFlags int32

const (
	LineFlagsNone     LineFlags = 0
	LineFlagsSegments LineFlags = 1024
	LineFlagsLoop     LineFlags = 2048
	LineFlagsSkipNaN  LineFlags = 4096
	LineFlagsNoClip   LineFlags = 8192
	LineFlagsShaded   LineFlags = 16384
)

// original name: ImPlotLocation_
type Location int32

const (
	LocationCenter    Location = 0
	LocationNorth     Location = 1
	LocationSouth     Location = 2
	LocationWest      Location = 4
	LocationEast      Location = 8
	LocationNorthWest Location = 5
	LocationNorthEast Location = 9
	LocationSouthWest Location = 6
	LocationSouthEast Location = 10
)

// original name: ImPlotMarker_
type Marker int32

const (
	MarkerNone     Marker = -1
	MarkerCircle   Marker = 0
	MarkerSquare   Marker = 1
	MarkerDiamond  Marker = 2
	MarkerUp       Marker = 3
	MarkerDown     Marker = 4
	MarkerLeft     Marker = 5
	MarkerRight    Marker = 6
	MarkerCross    Marker = 7
	MarkerPlus     Marker = 8
	MarkerAsterisk Marker = 9
	MarkerCOUNT    Marker = 10
)

// original name: ImPlotMouseTextFlags_
type MouseTextFlags int32

const (
	MouseTextFlagsNone       MouseTextFlags = 0
	MouseTextFlagsNoAuxAxes  MouseTextFlags = 1
	MouseTextFlagsNoFormat   MouseTextFlags = 2
	MouseTextFlagsShowAlways MouseTextFlags = 4
)

// original name: ImPlotPieChartFlags_
type PieChartFlags int32

const (
	PieChartFlagsNone         PieChartFlags = 0
	PieChartFlagsNormalize    PieChartFlags = 1024
	PieChartFlagsIgnoreHidden PieChartFlags = 2048
	PieChartFlagsExploding    PieChartFlags = 4096
)

// original name: ImPlotScale_
type Scale int32

const (
	ScaleLinear Scale = 0
	ScaleTime   Scale = 1
	ScaleLog10  Scale = 2
	ScaleSymLog Scale = 3
)

// original name: ImPlotScatterFlags_
type ScatterFlags int32

const (
	ScatterFlagsNone   ScatterFlags = 0
	ScatterFlagsNoClip ScatterFlags = 1024
)

// original name: ImPlotShadedFlags_
type ShadedFlags int32

const (
	ShadedFlagsNone ShadedFlags = 0
)

// original name: ImPlotStairsFlags_
type StairsFlags int32

const (
	StairsFlagsNone    StairsFlags = 0
	StairsFlagsPreStep StairsFlags = 1024
	StairsFlagsShaded  StairsFlags = 2048
)

// original name: ImPlotStemsFlags_
type StemsFlags int32

const (
	StemsFlagsNone       StemsFlags = 0
	StemsFlagsHorizontal StemsFlags = 1024
)

// original name: ImPlotStyleVar_
type StyleVar int32

const (
	StyleVarLineWeight         StyleVar = 0
	StyleVarMarker             StyleVar = 1
	StyleVarMarkerSize         StyleVar = 2
	StyleVarMarkerWeight       StyleVar = 3
	StyleVarFillAlpha          StyleVar = 4
	StyleVarErrorBarSize       StyleVar = 5
	StyleVarErrorBarWeight     StyleVar = 6
	StyleVarDigitalBitHeight   StyleVar = 7
	StyleVarDigitalBitGap      StyleVar = 8
	StyleVarPlotBorderSize     StyleVar = 9
	StyleVarMinorAlpha         StyleVar = 10
	StyleVarMajorTickLen       StyleVar = 11
	StyleVarMinorTickLen       StyleVar = 12
	StyleVarMajorTickSize      StyleVar = 13
	StyleVarMinorTickSize      StyleVar = 14
	StyleVarMajorGridSize      StyleVar = 15
	StyleVarMinorGridSize      StyleVar = 16
	StyleVarPlotPadding        StyleVar = 17
	StyleVarLabelPadding       StyleVar = 18
	StyleVarLegendPadding      StyleVar = 19
	StyleVarLegendInnerPadding StyleVar = 20
	StyleVarLegendSpacing      StyleVar = 21
	StyleVarMousePosPadding    StyleVar = 22
	StyleVarAnnotationPadding  StyleVar = 23
	StyleVarFitPadding         StyleVar = 24
	StyleVarPlotDefaultSize    StyleVar = 25
	StyleVarPlotMinSize        StyleVar = 26
	StyleVarCOUNT              StyleVar = 27
)

// original name: ImPlotSubplotFlags_
type SubplotFlags int32

const (
	SubplotFlagsNone       SubplotFlags = 0
	SubplotFlagsNoTitle    SubplotFlags = 1
	SubplotFlagsNoLegend   SubplotFlags = 2
	SubplotFlagsNoMenus    SubplotFlags = 4
	SubplotFlagsNoResize   SubplotFlags = 8
	SubplotFlagsNoAlign    SubplotFlags = 16
	SubplotFlagsShareItems SubplotFlags = 32
	SubplotFlagsLinkRows   SubplotFlags = 64
	SubplotFlagsLinkCols   SubplotFlags = 128
	SubplotFlagsLinkAllX   SubplotFlags = 256
	SubplotFlagsLinkAllY   SubplotFlags = 512
	SubplotFlagsColMajor   SubplotFlags = 1024
)

// original name: ImPlotTextFlags_
type TextFlags int32

const (
	TextFlagsNone     TextFlags = 0
	TextFlagsVertical TextFlags = 1024
)

// original name: ImPlotTimeFmt_
type TimeFmt int32

const (
	TimeFmtNone     TimeFmt = 0
	TimeFmtUs       TimeFmt = 1
	TimeFmtSUs      TimeFmt = 2
	TimeFmtSMs      TimeFmt = 3
	TimeFmtS        TimeFmt = 4
	TimeFmtMinSMs   TimeFmt = 5
	TimeFmtHrMinSMs TimeFmt = 6
	TimeFmtHrMinS   TimeFmt = 7
	TimeFmtHrMin    TimeFmt = 8
	TimeFmtHr       TimeFmt = 9
)

// original name: ImPlotTimeUnit_
type TimeUnit int32

const (
	TimeUnitUs    TimeUnit = 0
	TimeUnitMs    TimeUnit = 1
	TimeUnitS     TimeUnit = 2
	TimeUnitMin   TimeUnit = 3
	TimeUnitHr    TimeUnit = 4
	TimeUnitDay   TimeUnit = 5
	TimeUnitMo    TimeUnit = 6
	TimeUnitYr    TimeUnit = 7
	TimeUnitCOUNT TimeUnit = 8
)
