// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package opengl3

import (
	"github.com/AllenDang/cimgui-go/imgui"
	"github.com/AllenDang/cimgui-go/internal"
)

// #include "structs_accessor.h"
// #include "wrapper.h"
// #include "../../imgui/extra_types.h"
import "C"

func ImplOpenGL3NewFrame() {
	C.ImGui_ImplOpenGL3_NewFrame()
}

func ImplOpenGL3RenderDrawData(draw_data *imgui.DrawData) {
	draw_dataArg, draw_dataFin := draw_data.Handle()
	C.ImGui_ImplOpenGL3_RenderDrawData(internal.ReinterpretCast[*C.ImDrawData](draw_dataArg))

	draw_dataFin()
}

func ImplOpenGL3Shutdown() {
	C.ImGui_ImplOpenGL3_Shutdown()
}

func ImplOpenGL3Init() bool {
	return C.wrap_ImGui_ImplOpenGL3_Init() == C.bool(true)
}
