// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

#include "wrapper.h"
#include "../../cwrappers/cimgui_impl.h"

bool wrap_ImGui_ImplOpenGL3_Init() { return ImGui_ImplOpenGL3_Init(0); }
