// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

#pragma once

#include "../../cwrappers/cimgui.h"
#include "../../cwrappers/cimgui_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern bool wrap_ImGui_ImplOpenGL3_Init();

#ifdef __cplusplus
}
#endif
