// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package mypkg

// #include "structs_accessor.h"
// #include "wrapper.h"

import "C"

func (self B) SetField1(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_B_SetField1(selfArg, C.int(v))
}

func (self *B) Field1() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_B_GetField1(internal.ReinterpretCast[*C.B](selfArg)))
}

func (self B) SetField2(v A) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_B_SetField2(selfArg, C.A(v))
}

func (self *B) Field2() A {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return A(C.wrap_B_GetField2(internal.ReinterpretCast[*C.B](selfArg)))
}
