// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package cimgui

// #include "cimplot_wrapper.h"
import "C"
import "unsafe"

type PlotAlignmentData uintptr

func (data PlotAlignmentData) handle() *C.ImPlotAlignmentData {
	return (*C.ImPlotAlignmentData)(unsafe.Pointer(data))
}

func (data PlotAlignmentData) c() C.ImPlotAlignmentData {
	return *(data.handle())
}

func newImPlotAlignmentDataFromC(cvalue C.ImPlotAlignmentData) PlotAlignmentData {
	return PlotAlignmentData(unsafe.Pointer(&cvalue))
}

type PlotAnnotation uintptr

func (data PlotAnnotation) handle() *C.ImPlotAnnotation {
	return (*C.ImPlotAnnotation)(unsafe.Pointer(data))
}

func (data PlotAnnotation) c() C.ImPlotAnnotation {
	return *(data.handle())
}

func newImPlotAnnotationFromC(cvalue C.ImPlotAnnotation) PlotAnnotation {
	return PlotAnnotation(unsafe.Pointer(&cvalue))
}

type PlotAnnotationCollection uintptr

func (data PlotAnnotationCollection) handle() *C.ImPlotAnnotationCollection {
	return (*C.ImPlotAnnotationCollection)(unsafe.Pointer(data))
}

func (data PlotAnnotationCollection) c() C.ImPlotAnnotationCollection {
	return *(data.handle())
}

func newImPlotAnnotationCollectionFromC(cvalue C.ImPlotAnnotationCollection) PlotAnnotationCollection {
	return PlotAnnotationCollection(unsafe.Pointer(&cvalue))
}

type PlotAxis uintptr

func (data PlotAxis) handle() *C.ImPlotAxis {
	return (*C.ImPlotAxis)(unsafe.Pointer(data))
}

func (data PlotAxis) c() C.ImPlotAxis {
	return *(data.handle())
}

func newImPlotAxisFromC(cvalue C.ImPlotAxis) PlotAxis {
	return PlotAxis(unsafe.Pointer(&cvalue))
}

type PlotColormapData uintptr

func (data PlotColormapData) handle() *C.ImPlotColormapData {
	return (*C.ImPlotColormapData)(unsafe.Pointer(data))
}

func (data PlotColormapData) c() C.ImPlotColormapData {
	return *(data.handle())
}

func newImPlotColormapDataFromC(cvalue C.ImPlotColormapData) PlotColormapData {
	return PlotColormapData(unsafe.Pointer(&cvalue))
}

type PlotContext uintptr

func (data PlotContext) handle() *C.ImPlotContext {
	return (*C.ImPlotContext)(unsafe.Pointer(data))
}

func (data PlotContext) c() C.ImPlotContext {
	return *(data.handle())
}

func newImPlotContextFromC(cvalue C.ImPlotContext) PlotContext {
	return PlotContext(unsafe.Pointer(&cvalue))
}

type PlotDateTimeSpec uintptr

func (data PlotDateTimeSpec) handle() *C.ImPlotDateTimeSpec {
	return (*C.ImPlotDateTimeSpec)(unsafe.Pointer(data))
}

func (data PlotDateTimeSpec) c() C.ImPlotDateTimeSpec {
	return *(data.handle())
}

func newImPlotDateTimeSpecFromC(cvalue C.ImPlotDateTimeSpec) PlotDateTimeSpec {
	return PlotDateTimeSpec(unsafe.Pointer(&cvalue))
}

type PlotInputMap uintptr

func (data PlotInputMap) handle() *C.ImPlotInputMap {
	return (*C.ImPlotInputMap)(unsafe.Pointer(data))
}

func (data PlotInputMap) c() C.ImPlotInputMap {
	return *(data.handle())
}

func newImPlotInputMapFromC(cvalue C.ImPlotInputMap) PlotInputMap {
	return PlotInputMap(unsafe.Pointer(&cvalue))
}

type PlotItem uintptr

func (data PlotItem) handle() *C.ImPlotItem {
	return (*C.ImPlotItem)(unsafe.Pointer(data))
}

func (data PlotItem) c() C.ImPlotItem {
	return *(data.handle())
}

func newImPlotItemFromC(cvalue C.ImPlotItem) PlotItem {
	return PlotItem(unsafe.Pointer(&cvalue))
}

type PlotItemGroup uintptr

func (data PlotItemGroup) handle() *C.ImPlotItemGroup {
	return (*C.ImPlotItemGroup)(unsafe.Pointer(data))
}

func (data PlotItemGroup) c() C.ImPlotItemGroup {
	return *(data.handle())
}

func newImPlotItemGroupFromC(cvalue C.ImPlotItemGroup) PlotItemGroup {
	return PlotItemGroup(unsafe.Pointer(&cvalue))
}

type PlotLegend uintptr

func (data PlotLegend) handle() *C.ImPlotLegend {
	return (*C.ImPlotLegend)(unsafe.Pointer(data))
}

func (data PlotLegend) c() C.ImPlotLegend {
	return *(data.handle())
}

func newImPlotLegendFromC(cvalue C.ImPlotLegend) PlotLegend {
	return PlotLegend(unsafe.Pointer(&cvalue))
}

type PlotNextItemData uintptr

func (data PlotNextItemData) handle() *C.ImPlotNextItemData {
	return (*C.ImPlotNextItemData)(unsafe.Pointer(data))
}

func (data PlotNextItemData) c() C.ImPlotNextItemData {
	return *(data.handle())
}

func newImPlotNextItemDataFromC(cvalue C.ImPlotNextItemData) PlotNextItemData {
	return PlotNextItemData(unsafe.Pointer(&cvalue))
}

type PlotNextPlotData uintptr

func (data PlotNextPlotData) handle() *C.ImPlotNextPlotData {
	return (*C.ImPlotNextPlotData)(unsafe.Pointer(data))
}

func (data PlotNextPlotData) c() C.ImPlotNextPlotData {
	return *(data.handle())
}

func newImPlotNextPlotDataFromC(cvalue C.ImPlotNextPlotData) PlotNextPlotData {
	return PlotNextPlotData(unsafe.Pointer(&cvalue))
}

type PlotPlot uintptr

func (data PlotPlot) handle() *C.ImPlotPlot {
	return (*C.ImPlotPlot)(unsafe.Pointer(data))
}

func (data PlotPlot) c() C.ImPlotPlot {
	return *(data.handle())
}

func newImPlotPlotFromC(cvalue C.ImPlotPlot) PlotPlot {
	return PlotPlot(unsafe.Pointer(&cvalue))
}

type PlotPointError uintptr

func (data PlotPointError) handle() *C.ImPlotPointError {
	return (*C.ImPlotPointError)(unsafe.Pointer(data))
}

func (data PlotPointError) c() C.ImPlotPointError {
	return *(data.handle())
}

func newImPlotPointErrorFromC(cvalue C.ImPlotPointError) PlotPointError {
	return PlotPointError(unsafe.Pointer(&cvalue))
}

type PlotRange uintptr

func (data PlotRange) handle() *C.ImPlotRange {
	return (*C.ImPlotRange)(unsafe.Pointer(data))
}

func (data PlotRange) c() C.ImPlotRange {
	return *(data.handle())
}

func newImPlotRangeFromC(cvalue C.ImPlotRange) PlotRange {
	return PlotRange(unsafe.Pointer(&cvalue))
}

type PlotRect uintptr

func (data PlotRect) handle() *C.ImPlotRect {
	return (*C.ImPlotRect)(unsafe.Pointer(data))
}

func (data PlotRect) c() C.ImPlotRect {
	return *(data.handle())
}

func newImPlotRectFromC(cvalue C.ImPlotRect) PlotRect {
	return PlotRect(unsafe.Pointer(&cvalue))
}

type PlotStyle uintptr

func (data PlotStyle) handle() *C.ImPlotStyle {
	return (*C.ImPlotStyle)(unsafe.Pointer(data))
}

func (data PlotStyle) c() C.ImPlotStyle {
	return *(data.handle())
}

func newImPlotStyleFromC(cvalue C.ImPlotStyle) PlotStyle {
	return PlotStyle(unsafe.Pointer(&cvalue))
}

type PlotSubplot uintptr

func (data PlotSubplot) handle() *C.ImPlotSubplot {
	return (*C.ImPlotSubplot)(unsafe.Pointer(data))
}

func (data PlotSubplot) c() C.ImPlotSubplot {
	return *(data.handle())
}

func newImPlotSubplotFromC(cvalue C.ImPlotSubplot) PlotSubplot {
	return PlotSubplot(unsafe.Pointer(&cvalue))
}

type PlotTag uintptr

func (data PlotTag) handle() *C.ImPlotTag {
	return (*C.ImPlotTag)(unsafe.Pointer(data))
}

func (data PlotTag) c() C.ImPlotTag {
	return *(data.handle())
}

func newImPlotTagFromC(cvalue C.ImPlotTag) PlotTag {
	return PlotTag(unsafe.Pointer(&cvalue))
}

type PlotTagCollection uintptr

func (data PlotTagCollection) handle() *C.ImPlotTagCollection {
	return (*C.ImPlotTagCollection)(unsafe.Pointer(data))
}

func (data PlotTagCollection) c() C.ImPlotTagCollection {
	return *(data.handle())
}

func newImPlotTagCollectionFromC(cvalue C.ImPlotTagCollection) PlotTagCollection {
	return PlotTagCollection(unsafe.Pointer(&cvalue))
}

type PlotTick uintptr

func (data PlotTick) handle() *C.ImPlotTick {
	return (*C.ImPlotTick)(unsafe.Pointer(data))
}

func (data PlotTick) c() C.ImPlotTick {
	return *(data.handle())
}

func newImPlotTickFromC(cvalue C.ImPlotTick) PlotTick {
	return PlotTick(unsafe.Pointer(&cvalue))
}

type PlotTicker uintptr

func (data PlotTicker) handle() *C.ImPlotTicker {
	return (*C.ImPlotTicker)(unsafe.Pointer(data))
}

func (data PlotTicker) c() C.ImPlotTicker {
	return *(data.handle())
}

func newImPlotTickerFromC(cvalue C.ImPlotTicker) PlotTicker {
	return PlotTicker(unsafe.Pointer(&cvalue))
}

type PlotTime uintptr

func (data PlotTime) handle() *C.ImPlotTime {
	return (*C.ImPlotTime)(unsafe.Pointer(data))
}

func (data PlotTime) c() C.ImPlotTime {
	return *(data.handle())
}

func newImPlotTimeFromC(cvalue C.ImPlotTime) PlotTime {
	return PlotTime(unsafe.Pointer(&cvalue))
}
