// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

#pragma once

#include "../../cwrappers/cimgui.h"
#include "../../cwrappers/cimgui_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern bool wrap_ImGui_ImplSDL2_InitForOpenGL(SDL_Window* window,uintptr_t sdl_gl_context);
extern void wrap_ImGui_ImplSDL2_SetGamepadMode(ImGui_ImplSDL2_GamepadMode mode);

#ifdef __cplusplus
}
#endif
