all:
	mkdir -p output
	cd output; \
		go run ../.. --verbose --package mypkg --include header.h --preset ..//preset.json -lng -lg -d ../deffinitions.json -e ../structs_and_enums.json -t ../typedefs_dict.json
