name: Compile cimgui for windows

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - name: configure
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DIMGUI_STATIC=On
      working-directory: .\cimgui

    - name: make
      run: cmake --build .\build --config Release --parallel 4
      working-directory: .\cimgui

    - name: copy to lib
      run: |
        mkdir ${{runner.workspace}}\cimgui-go\lib\windows\x64
        Copy-Item "${{runner.workspace}}\cimgui-go\cimgui\build\Release\cimgui.lib" -Destination "${{runner.workspace}}\cimgui-go\lib\windows\x64\cimgui.a" -Force

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update windows lib from ci
