name: Compile cimgui for linux

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: configure
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DIMGUI_STATIC=On
      working-directory: ./cimgui
    - name: make
      run: make
      working-directory: ./cimgui/build
    - name: copy to lib
      run: |
        mkdir -p ./lib/linux/x64
        cp -f ./cimgui/build/cimgui.a ./lib/linux/x64/
        git add .
        git commit -m "Update linux lib from CI"
        git push
