name: Compile cimgui for macos

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@main

    - name: configure glfw for x64
      run: cmake -S . -Bbuild -DCMAKE_OSX_ARCHITECTURES=x86_64
      working-directory: ./thirdparty/glfw

    - name: make glfw x84
      run: make
      working-directory: ./thirdparty/glfw/build

    - name: copy glfw to lib
      run: |
        cp -f ./thirdparty/glfw/build/src/libglfw3.a ./lib/macos/x64

    - name: clean glfw
      run: cmake --build ./build --target clean
      working-directory: ./thirdparty/glfw

    - name: configure glfw for arm64
      run: cmake -S . -Bbuild -DCMAKE_OSX_ARCHITECTURES=arm64
      working-directory: ./thirdparty/glfw

    - name: make glfw arm64
      run: make
      working-directory: ./thirdparty/glfw/build

    - name: copy glfw to lib
      run: |
        cp -f ./thirdparty/glfw/build/src/libglfw3.a ./lib/macos/arm64

    - name: configure cimgui for x64
      run: cmake -Bbuild -DCMAKE_OSX_ARCHITECTURES=x86_64
      working-directory: ./lib

    - name: make cimgui for x64
      run: make
      working-directory: ./lib/build

    - name: copy cimgui x64 to lib
      run: |
        mkdir -p ./lib/macos/x64
        cp -f ./lib/build/cimgui.a ./lib/macos/x64/

    - name: clean up
      run: cmake --build ./build --target clean
      working-directory: ./lib

    - name: configure cimgui for arm64
      run: cmake -Bbuild -DCMAKE_OSX_ARCHITECTURES=arm64
      working-directory: ./lib

    - name: make cimgui for arm64
      run: make
      working-directory: ./lib/build

    - name: copy cimgui arm64 to lib
      run: |
        mkdir -p ./lib/macos/arm64
        cp -f ./lib/build/cimgui.a ./lib/macos/arm64/

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        push_options: '--force'
        commit_message: Update macos lib from ci
