name: Compile cimgui for windows

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - uses: ashutoshvarma/action-cmake-build@master
      with:
        source-dir: ${{runner.workspace}}/cimgui
        build-dir: ${{runner.workspace}}/cimgui/build
        build-type: Release
        configure-options: -DIMGUI_STATIC=On

    - name: copy to lib
      run: |
        mkdir .\lib\windows\x64
        copy /Y .\cimgui\build\cimgui.a .\lib\windows\x64\

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update windows lib from ci
