name: Compile cimgui for linux

on:
  workflow_dispatch:

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: add libs for glfw
      run: sudo apt-get install -y libXcursor-devel libXi-devel libXinerama-devel libXrandr-devel

    - name: configure glfw
      run: cmake -S . -Bbuild
      working-directory: ./thirdparty/glfw

    - name: make glfw
      run: make
      working-directory: ./thirdparty/glfw/build

    - name: copy glfw to lib
      run: |
        cp -f ./thirdparty/glfw/build/src/libglfw3.a ./lib/linux/x64

    - name: configure cimgui
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DIMGUI_STATIC=On
      working-directory: ./cimgui

    - name: make cimgui
      run: make
      working-directory: ./cimgui/build

    - name: copy cimgui to lib
      run: |
        mkdir -p ./lib/linux/x64
        cp -f ./cimgui/build/cimgui.a ./lib/linux/x64/

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update linux lib from ci
