name: Compile cimgui for linux

on:
  workflow_dispatch:

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@main

    - name: add libs for glfw
      run: sudo apt install xorg-dev

    - name: configure glfw
      run: cmake -S . -Bbuild
      working-directory: ./thirdparty/glfw

    - name: make glfw
      run: make
      working-directory: ./thirdparty/glfw/build

    - name: copy glfw to lib
      run: |
        cp -f ./thirdparty/glfw/build/src/libglfw3.a ./lib/linux/x64

    - name: configure cimgui
      run: cmake -Bbuild
      working-directory: ./lib

    - name: make cimgui
      run: make
      working-directory: ./lib/build

    - name: copy cimgui to lib
      run: |
        mkdir -p ./lib/linux/x64
        cp -f ./lib/build/cimgui.a ./lib/linux/x64/

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        push_options: '--force'
        commit_message: Update linux lib from ci
