name: Compile cimgui for windows

on:
  workflow_dispatch:

jobs:
  build-windows-x64:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@main

    - name: Install MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p

    - name: configure glfw
      run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release
      working-directory: ./thirdparty/glfw

    - name: make glfw
      run: cmake --build build
      working-directory: ./thirdparty/glfw

    - name: copy glfw to lib
      run: cp -f ./thirdparty/glfw/build/src/libglfw3.a ./lib/windows/x64

    - name: configure cimgui
      run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DIMGUI_STATIC=On
      working-directory: .\cimgui

    - name: make cimgui
      run: cmake --build build
      working-directory: .\cimgui

    - name: copy cimgui to lib
      run: cp -f ./cimgui/build/cimgui.a ./lib/windows/x64/

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update windows lib from ci
