name: "Test source code"

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  RunGoTests:
    # I use MacOS, becuse it doesn't need additional libs (in contrast to linux).
    runs-on: macos-latest
    steps:
      # uncomment and put anywhere to start SSH session
      #- name: SSH Debug
      #  uses: mxschmitt/action-tmate@v3
      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Checkout out source code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Run GO test
        run: go test -race -v ./...
